In [62]:
from pathlib import Path

root = Path().resolve()
root

PosixPath('/Users/hiraokatatsuru/Library/Mobile Documents/com~apple~CloudDocs/postal-operation-shift-management-system/notebooks')

In [63]:
from pathlib import Path
import pandas as pd
from IPython.display import display

# 今のノートブックは /.../postal-operation-shift-management-system/notebooks/ にある
# なので、1つ親に上がるとプロジェクトルート
notebook_dir = Path().resolve()
project_root = notebook_dir.parent

project_root

PosixPath('/Users/hiraokatatsuru/Library/Mobile Documents/com~apple~CloudDocs/postal-operation-shift-management-system')

In [64]:
csv_dir = project_root / "excel_templates" / "export_csv"
csv_dir, csv_dir.exists()

(PosixPath('/Users/hiraokatatsuru/Library/Mobile Documents/com~apple~CloudDocs/postal-operation-shift-management-system/excel_templates/export_csv'),
 True)

In [65]:
df_emp     = pd.read_csv(csv_dir / "employees.csv", encoding="cp932")
df_zone    = pd.read_csv(csv_dir / "zones.csv", encoding="cp932")
df_need    = pd.read_csv(csv_dir / "employee_demand.csv", encoding="cp932")
df_ft      = pd.read_csv(csv_dir / "jobtype_fulltime.csv", encoding="cp932")
df_pt      = pd.read_csv(csv_dir / "jobtype_parttime.csv", encoding="cp932")
df_meta    = pd.read_csv(csv_dir / "shift_meta.csv", encoding="cp932")
df_leave   = pd.read_csv(csv_dir / "leave_types.csv", encoding="cp932")
df_special = pd.read_csv(csv_dir / "special_marks.csv", encoding="cp932")
df_pre = pd.read_csv(csv_dir / "pre_assignments.csv",
                     encoding="cp932")

display(df_emp.head())
display(df_zone.head())
display(df_need.head())
display(df_ft.head())
display(df_pt.head())
display(df_meta.head())
display(df_leave.head())
display(df_special.head())
display(df_pre.head())

   社員番号     氏名        部   班 社員タイプ    役職  班長  副班長  認証司  勤務時間(日)  勤務時間(月)
0     1  社員1_1  第一集配営業部  1班   正社員  課長代理   1    0    1        8      160
1     2  社員1_2  第一集配営業部  1班   正社員    主任   0    0    0        8      160
2     3  社員1_3  第一集配営業部  1班   正社員    主任   0    0    0        8      160
3     4  社員1_4  第一集配営業部  1班   正社員    主任   0    0    0        8      160
4     5  社員1_5  第一集配営業部  1班   正社員    一般   0    0    0        8      160

  区コード   区名   班  稼働   月   火   水   木   金  土  日  祝 シフトタイプ
0   Z1   1区  1班  通配  10  10  10  10  10  0  0  0     早番
1   Z2   2区  1班  通配  10  10  10  10  10  0  0  0     早番
2   Z3   3区  1班  通配  10  10  10  10  10  0  0  0     日勤
3   Z4   4区  1班  通配  10   9   9   9   9  0  0  0     日勤
4   Z5  大口1  1班  混合  10  10  10  10  10  0  0  0     早番

,社員番号,氏名,1区,2区,3区,4区,大口1,大口1-3,補助,速早,...,金,土,日,祝,早番,日勤,中勤,夜勤,夜勤(土),夜勤(日)
0,1,社員1_1,3,3,3,3,4,4,3,0,...,1,0,0,0,早1,日1,日3,日5,中1,日3
1,2,社員1_2,3,3,4,4,0,2,3,4,...,1,1,1,1,早1,日1,日3,日5,中1,日3
2,3,社員1_3,4,4,3,3,0,2,2,3,...,1,1,1,1,早1,日1,日3,日5,中1,日3
3,4,社員1_4,3,4,3,3,0,3,2,3,...,1,1,1,1,早1,日1,日3,日5,中1,日3
4,5,社員1_5,3,4,4,3,3,4,3,4,...,1,1,1,1,早1,日1,日3,日5,中1,日3

  勤務名 就労開始時間 就労終了時間  勤務時間
0  早1   6:30  15:15     8
1  早2   7:00  15:45     8
2  早3   7:30  16:15     8
3  早4   7:45  16:30     8
4  日1   8:00  16:45     8

  勤務名 就労開始時間 就労終了時間  勤務時間
0  早1   7:30  15:15     7
1  早2   7:30  16:15     8
2  早3   7:30  17:30     9
3  日1   8:00  11:00     3
4  日2   8:00  12:00     4

   start_date
0  2025-11-16

  leave_name
0         非番
1         週休
2         祝休
3         計年
4         年休

Empty DataFrame
Columns: [emp_no, date, kind]
Index: []

   emp_no        date row_kind value
0       1  2025-11-19    lower    計年
1       2  2025-12-02    lower    計年
2       3  2025-12-09    lower    計年
3       4  2025-11-26    lower    計年
4       5  2025-11-21    lower    計年

In [66]:
I = list(df_emp['社員番号'])
I

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [67]:
#全ての業務
K = df_zone.loc[df_zone['稼働'].isin(['通配', '混合', '組立', '指定業務']), '区名'].tolist()
K

['1区',
 '2区',
 '3区',
 '4区',
 '大口1',
 '大口1-3',
 '補助',
 '速早',
 '速夜',
 '速夜(土)',
 '速夜(日)',
 '速夜(祝)',
 '組立',
 '通区訓練',
 '出張',
 '営業']

In [68]:
#ソルバーが選ぶことができる業務(指定業務を抜いた状態)
selected_jobs = df_zone.loc[df_zone['稼働'].isin(['通配', '混合', '組立']), '区名'].tolist()
selected_jobs

['1区',
 '2区',
 '3区',
 '4区',
 '大口1',
 '大口1-3',
 '補助',
 '速早',
 '速夜',
 '速夜(土)',
 '速夜(日)',
 '速夜(祝)',
 '組立']

In [69]:
R = list(df_leave['leave_name'])
R

['非番',
 '週休',
 '祝休',
 '計年',
 '年休',
 '夏期',
 '冬期',
 '代休',
 '承欠',
 '産休',
 '育休',
 '介護',
 '病休',
 '休職',
 'その他']

In [70]:
special_attendance = ['廃休', 'マル超']
special_attendance

['廃休', 'マル超']

In [71]:
start_date = df_meta['start_date'][0]
start_date

'2025-11-16'

In [72]:
import jpholiday
# 日曜日から始まる28日間の日付を生成
#start_date = date 
D = pd.date_range(start=start_date, periods=28)

# 祝日判定のマスク（True=祝日, False=祝日以外） --- jpholiday は要インストール
is_holiday_mask = D.map(jpholiday.is_holiday)

# 曜日判定用に、Pandas の weekday 属性を利用
weekday_series = D.weekday  # Returns an ndarray of 0=Mon ... 6=Sun

# ① 祝日だけを抽出（DatetimeIndex のまま）
D_holiday = D[is_holiday_mask]

# ② 平日だけを抽出
#    - まず「祝日でない」こと
#    - かつ weekday が 0〜4 の範囲
mask_weekday = (~is_holiday_mask) & (weekday_series < 5)
D_weekday = D[mask_weekday]

# ③ 土曜日だけを抽出
mask_saturday = (~is_holiday_mask) & (weekday_series == 5)
D_saturday = D[mask_saturday]

# ④ 日曜日だけを抽出
mask_sunday = (~is_holiday_mask) & (weekday_series == 6)
D_sunday = D[mask_sunday]

# 結果を確認
print("元のDatetimeIndex D:")
print(D, "\n")

print("平日の DatetimeIndex:")
print(D_weekday, "\n")

print("土曜の DatetimeIndex:")
print(D_saturday, "\n")

print("日曜の DatetimeIndex:")
print(D_sunday, "\n")

print("祝日の DatetimeIndex:")
print(D_holiday, "\n")

元のDatetimeIndex D:
DatetimeIndex(['2025-11-16', '2025-11-17', '2025-11-18', '2025-11-19',
               '2025-11-20', '2025-11-21', '2025-11-22', '2025-11-23',
               '2025-11-24', '2025-11-25', '2025-11-26', '2025-11-27',
               '2025-11-28', '2025-11-29', '2025-11-30', '2025-12-01',
               '2025-12-02', '2025-12-03', '2025-12-04', '2025-12-05',
               '2025-12-06', '2025-12-07', '2025-12-08', '2025-12-09',
               '2025-12-10', '2025-12-11', '2025-12-12', '2025-12-13'],
              dtype='datetime64[ns]', freq='D')

平日の DatetimeIndex:
DatetimeIndex(['2025-11-17', '2025-11-18', '2025-11-19', '2025-11-20',
               '2025-11-21', '2025-11-25', '2025-11-26', '2025-11-27',
               '2025-11-28', '2025-12-01', '2025-12-02', '2025-12-03',
               '2025-12-04', '2025-12-05', '2025-12-08', '2025-12-09',
               '2025-12-10', '2025-12-11', '2025-12-12'],
              dtype='datetime64[ns]', freq=None)

土曜の DatetimeIndex:
DatetimeIndex(['2025-11-22', '2025-11-29', '2025-12-06', '2025-12-13'], dtype='datetime64[ns]', freq=None)

日曜の DatetimeIndex:
DatetimeIndex(['2025-11-16', '2025-11-30', '2025-12-07'], dtype='datetime64[ns]', freq=None)

祝日の DatetimeIndex:
DatetimeIndex(['2025-11-23', '2025-11-24'], dtype='datetime64[ns]', freq='D')

In [73]:
# 週ごとに分割（7日単位）
W = [D[i:i+7] for i in range(0, len(D), 7)]
W

[DatetimeIndex(['2025-11-16', '2025-11-17', '2025-11-18', '2025-11-19',
                '2025-11-20', '2025-11-21', '2025-11-22'],
               dtype='datetime64[ns]', freq='D'),
 DatetimeIndex(['2025-11-23', '2025-11-24', '2025-11-25', '2025-11-26',
                '2025-11-27', '2025-11-28', '2025-11-29'],
               dtype='datetime64[ns]', freq='D'),
 DatetimeIndex(['2025-11-30', '2025-12-01', '2025-12-02', '2025-12-03',
                '2025-12-04', '2025-12-05', '2025-12-06'],
               dtype='datetime64[ns]', freq='D'),
 DatetimeIndex(['2025-12-07', '2025-12-08', '2025-12-09', '2025-12-10',
                '2025-12-11', '2025-12-12', '2025-12-13'],
               dtype='datetime64[ns]', freq='D')]

In [74]:
selected_columns = ['社員番号'] + selected_jobs
subset_df = df_need[selected_columns]
#社員のできる業務を辞書化(ソルバーが選べる)
A = subset_df.set_index('社員番号') \
             .apply(lambda row: {k: v for k, v in row.items() if v > 0}, axis=1) \
             .to_dict()
A

{1: {'1区': 3,
  '2区': 3,
  '3区': 3,
  '4区': 3,
  '大口1': 4,
  '大口1-3': 4,
  '補助': 3,
  '速夜': 2},
 2: {'1区': 3,
  '2区': 3,
  '3区': 4,
  '4区': 4,
  '大口1-3': 2,
  '補助': 3,
  '速早': 4,
  '速夜': 2,
  '速夜(土)': 2,
  '速夜(日)': 2,
  '速夜(祝)': 2},
 3: {'1区': 4,
  '2区': 4,
  '3区': 3,
  '4区': 3,
  '大口1-3': 2,
  '補助': 2,
  '速早': 3,
  '速夜': 3,
  '速夜(土)': 4,
  '速夜(日)': 4,
  '速夜(祝)': 4},
 4: {'1区': 3,
  '2区': 4,
  '3区': 3,
  '4区': 3,
  '大口1-3': 3,
  '補助': 2,
  '速早': 3,
  '速夜': 4,
  '速夜(土)': 4,
  '速夜(日)': 4,
  '速夜(祝)': 4},
 5: {'1区': 3,
  '2区': 4,
  '3区': 4,
  '4区': 3,
  '大口1': 3,
  '大口1-3': 4,
  '補助': 3,
  '速早': 4,
  '速夜': 4,
  '速夜(土)': 4,
  '速夜(日)': 4,
  '速夜(祝)': 4},
 6: {'3区': 3, '4区': 3},
 7: {'1区': 3, '2区': 3, '3区': 3, '4区': 3},
 8: {'速夜': 5},
 9: {'大口1': 5},
 10: {'組立': 5}}

In [75]:
selected_columns = ['社員番号'] + K
subset_df = df_need[selected_columns]
#社員のできる業務を辞書化(指定のみ)
B = subset_df.set_index('社員番号') \
             .apply(lambda row: {k: v for k, v in row.items() if v == 0}, axis=1) \
             .to_dict()
B

{1: {'速早': 0,
  '速夜(土)': 0,
  '速夜(日)': 0,
  '速夜(祝)': 0,
  '組立': 0,
  '通区訓練': 0,
  '出張': 0,
  '営業': 0},
 2: {'大口1': 0, '組立': 0, '通区訓練': 0, '出張': 0, '営業': 0},
 3: {'大口1': 0, '組立': 0, '通区訓練': 0, '出張': 0, '営業': 0},
 4: {'大口1': 0, '組立': 0, '通区訓練': 0, '出張': 0, '営業': 0},
 5: {'組立': 0, '通区訓練': 0, '出張': 0, '営業': 0},
 6: {'1区': 0,
  '2区': 0,
  '大口1': 0,
  '大口1-3': 0,
  '補助': 0,
  '速早': 0,
  '速夜': 0,
  '速夜(土)': 0,
  '速夜(日)': 0,
  '速夜(祝)': 0,
  '組立': 0,
  '通区訓練': 0,
  '出張': 0,
  '営業': 0},
 7: {'大口1': 0,
  '大口1-3': 0,
  '補助': 0,
  '速早': 0,
  '速夜': 0,
  '速夜(土)': 0,
  '速夜(日)': 0,
  '速夜(祝)': 0,
  '組立': 0,
  '通区訓練': 0,
  '出張': 0,
  '営業': 0},
 8: {'1区': 0,
  '2区': 0,
  '3区': 0,
  '4区': 0,
  '大口1': 0,
  '大口1-3': 0,
  '補助': 0,
  '速早': 0,
  '速夜(土)': 0,
  '速夜(日)': 0,
  '速夜(祝)': 0,
  '組立': 0,
  '通区訓練': 0,
  '出張': 0,
  '営業': 0},
 9: {'1区': 0,
  '2区': 0,
  '3区': 0,
  '4区': 0,
  '大口1-3': 0,
  '補助': 0,
  '速早': 0,
  '速夜': 0,
  '速夜(土)': 0,
  '速夜(日)': 0,
  '速夜(祝)': 0,
  '組立': 0,
  '通区訓練': 0,
  '出張': 0,
  '営業': 0},
 10: {'1区': 0,
  '2区': 0,
  '3区': 0,
  '4区': 0,
  '大口1': 0,
  '大口1-3': 0,
  '補助': 0,
  '速早': 0,
  '速夜': 0,
  '速夜(土)': 0,
  '速夜(日)': 0,
  '速夜(祝)': 0,
  '通区訓練': 0,
  '出張': 0,
  '営業': 0}}

In [76]:
# 曜日キーとして使いたい列名のリスト（順序が大事ならここで指定）
day_cols = ['月','火','水','木','金','土','日','祝']

# マッピングを作成
mapping = {
    day: df_zone.loc[df_zone[day] >= 1, '区名'].tolist()
    for day in day_cols
    if day in df_zone.columns
}

In [77]:
mapping

{'月': ['1区', '2区', '3区', '4区', '大口1', '大口1-3', '補助', '速夜', '組立'],
 '火': ['1区', '2区', '3区', '4区', '大口1', '大口1-3', '補助', '速夜', '組立'],
 '水': ['1区', '2区', '3区', '4区', '大口1', '大口1-3', '補助', '速夜', '組立'],
 '木': ['1区', '2区', '3区', '4区', '大口1', '大口1-3', '補助', '速夜', '組立'],
 '金': ['1区', '2区', '3区', '4区', '大口1', '大口1-3', '補助', '速夜', '組立'],
 '土': ['補助', '速早', '速夜(土)'],
 '日': ['速早', '速夜(日)'],
 '祝': ['補助', '速早', '速夜(祝)']}

In [78]:
selected_columns = ['社員番号'] + day_cols
subset_df = df_need[selected_columns]
#社員の出勤できる曜日を辞書化
C = subset_df.set_index('社員番号') \
             .apply(lambda row: {k: v for k, v in row.items() if v >= 0}, axis=1) \
             .to_dict()
C

{1: {'月': 1, '火': 1, '水': 1, '木': 1, '金': 1, '土': 0, '日': 0, '祝': 0},
 2: {'月': 1, '火': 1, '水': 1, '木': 1, '金': 1, '土': 1, '日': 1, '祝': 1},
 3: {'月': 1, '火': 1, '水': 1, '木': 1, '金': 1, '土': 1, '日': 1, '祝': 1},
 4: {'月': 1, '火': 1, '水': 1, '木': 1, '金': 1, '土': 1, '日': 1, '祝': 1},
 5: {'月': 1, '火': 1, '水': 1, '木': 1, '金': 1, '土': 1, '日': 1, '祝': 1},
 6: {'月': 1, '火': 1, '水': 1, '木': 1, '金': 1, '土': 0, '日': 0, '祝': 0},
 7: {'月': 1, '火': 1, '水': 1, '木': 1, '金': 1, '土': 0, '日': 0, '祝': 0},
 8: {'月': 1, '火': 0, '水': 0, '木': 1, '金': 1, '土': 0, '日': 0, '祝': 0},
 9: {'月': 1, '火': 1, '水': 1, '木': 1, '金': 1, '土': 0, '日': 0, '祝': 0},
 10: {'月': 1, '火': 1, '水': 1, '木': 1, '金': 1, '土': 0, '日': 0, '祝': 0}}

In [79]:
from pathlib import Path
import pandas as pd
import jpholiday
import pprint

pp = pprint.PrettyPrinter(width=120)

# =========================
#  CSV読み込み（文字コード自動）
# =========================
def read_csv_auto(path: Path, **kwargs) -> pd.DataFrame:
    last_err = None
    for enc in ("utf-8-sig", "cp932"):
        try:
            return pd.read_csv(path, encoding=enc, **kwargs)
        except UnicodeDecodeError as e:
            last_err = e
    raise last_err

def must_have_cols(df: pd.DataFrame, need: set[str], name: str):
    missing = need - set(df.columns)
    if missing:
        raise ValueError(f"{name}: missing columns {missing}. got={df.columns.tolist()}")

# =========================
#  パス設定
# =========================
notebook_dir = Path().resolve()
project_root = notebook_dir.parent
csv_dir = project_root / "excel_templates" / "export_csv"
print("csv_dir:", csv_dir, "exists:", csv_dir.exists())
if not csv_dir.exists():
    raise FileNotFoundError(csv_dir)

# =========================
#  shift_meta.csv → start_date → 28日 D を作る
# =========================
df_meta = read_csv_auto(csv_dir / "shift_meta.csv")
must_have_cols(df_meta, {"start_date"}, "shift_meta.csv")

start_date = pd.to_datetime(df_meta.loc[0, "start_date"]).normalize()
D = pd.date_range(start=start_date, periods=28).normalize()
shift_set = set(D)

print("start_date:", start_date)
print("D (28日):", D)

# --- 祝日・平日マスク（必要なら） ---
is_holiday_mask = pd.Series([jpholiday.is_holiday(d) for d in D], index=D)
weekday_series = pd.Series([d.weekday() for d in D], index=D)  # 0=Mon … 6=Sun

D_holiday   = D[is_holiday_mask.values]               # 祝日（※日曜も True になり得るが、jpholiday次第）
D_weekday   = D[(~is_holiday_mask).values & (weekday_series.values < 5)]
D_saturday  = D[(~is_holiday_mask).values & (weekday_series.values == 5)]
D_sunday    = D[(~is_holiday_mask).values & (weekday_series.values == 6)]

# =========================
#  employees.csv（emp_no→氏名の辞書：デバッグ用）
# =========================
df_emp = read_csv_auto(csv_dir / "employees.csv")

# emp_no列と氏名列は環境で列名が揺れることがあるので候補で探す
emp_no_col_candidates = ["emp_no", "社員番号", "社員No", "社員NO", "従業員番号"]
emp_name_col_candidates = ["name", "氏名", "社員名", "名前"]

def find_col(df, candidates):
    for c in candidates:
        if c in df.columns:
            return c
    return None

emp_no_col = find_col(df_emp, emp_no_col_candidates)
emp_name_col = find_col(df_emp, emp_name_col_candidates)

empno_to_name = {}
if emp_no_col is not None and emp_name_col is not None:
    s_emp = df_emp[[emp_no_col, emp_name_col]].copy()
    s_emp[emp_no_col] = s_emp[emp_no_col].astype(str).str.strip()
    s_emp[emp_name_col] = s_emp[emp_name_col].astype(str).str.strip()
    empno_to_name = dict(zip(s_emp[emp_no_col], s_emp[emp_name_col]))
else:
    print("NOTE: employees.csv から emp_no/氏名列が見つからず、名前表示は省略します。")
    print("employees.csv columns =", df_emp.columns.tolist())

# =========================
#  leave_types.csv → leave_codes
# =========================
df_leave = read_csv_auto(csv_dir / "leave_types.csv")
# 期待列は leave_name（VBA/EXE想定）
if "leave_name" not in df_leave.columns:
    # 代替候補
    alt = find_col(df_leave, ["休暇種類名", "休暇名"])
    if alt is None:
        raise ValueError(f"leave_types.csv: leave_name列が見つかりません。columns={df_leave.columns.tolist()}")
    df_leave = df_leave.rename(columns={alt: "leave_name"})

leave_codes = set(df_leave["leave_name"].astype(str).str.strip().tolist())

# =========================
#  zones.csv → zone_codes
# =========================
df_zone = read_csv_auto(csv_dir / "zones.csv")
zone_name_col = find_col(df_zone, ["区名", "zone_name", "name"])
if zone_name_col is None:
    print("zones.csv columns =", df_zone.columns.tolist())
    raise ValueError("zones.csv に区名列が見つかりません（候補: 区名/zone_name/name）")

zone_codes = set(df_zone[zone_name_col].astype(str).str.strip().tolist())

# =========================
#  pre_assignments.csv（上段＋下段）
#  形式: emp_no,date,row_kind,value
# =========================
df_pre = read_csv_auto(csv_dir / "pre_assignments.csv")
must_have_cols(df_pre, {"emp_no", "date", "row_kind", "value"}, "pre_assignments.csv")

df_pre["emp_no"] = df_pre["emp_no"].astype(str).str.strip()
df_pre["date"] = pd.to_datetime(df_pre["date"]).dt.normalize()
df_pre["row_kind"] = df_pre["row_kind"].astype(str).str.strip()
df_pre["value"] = df_pre["value"].astype(str).str.strip()

# 期間外は捨てる
df_pre = df_pre[df_pre["date"].isin(shift_set)].copy()
print("df_pre rows (after filtering by D):", len(df_pre))

# =========================
#  special_marks.csv（廃休/マル超）
#  形式: emp_no,date,kind
# =========================
special_path = csv_dir / "special_marks.csv"
if special_path.exists():
    df_special = read_csv_auto(special_path)
    must_have_cols(df_special, {"emp_no", "date", "kind"}, "special_marks.csv")

    df_special["emp_no"] = df_special["emp_no"].astype(str).str.strip()
    df_special["date"] = pd.to_datetime(df_special["date"]).dt.normalize()
    df_special["kind"] = df_special["kind"].astype(str).str.strip()

    df_special = df_special[df_special["date"].isin(shift_set)].copy()
else:
    df_special = pd.DataFrame({"emp_no": [], "date": [], "kind": []})

print("df_special rows (after filtering by D):", len(df_special))

# =========================
#  コードリスト（ここは“現行の仕様”に寄せる）
# =========================
SPECIAL_KINDS = {"廃休", "マル超"}  # 特別業務

# =========================
#  辞書の初期化（すべて emp_no キー）
# =========================
pre_dict_rest    = {}  # {(emp_no, date): 休暇コード}
pre_dict_work    = {}  # {(emp_no, date): 勤務コード(区名など)}
pre_dict_special = {}  # {(emp_no, date): 廃休/マル超}
pre_dict_time    = {}  # {(emp_no, date): 上段（時間帯等）}

# “未知コード”を拾っておく（入力ミス検出に使う）
pre_unknown_lower = []  # [(emp_no, date, value)]

# =========================
#  pre_assignments から辞書構築
# =========================
for _, row in df_pre.iterrows():
    emp = row["emp_no"]
    d   = row["date"]
    kind = row["row_kind"]   # "upper" / "lower"
    v = row["value"].strip()

    if v == "" or v.lower() == "nan":
        continue

    if kind == "upper":
        pre_dict_time[(emp, d)] = v

    elif kind == "lower":
        if v in SPECIAL_KINDS:
            pre_dict_special[(emp, d)] = v
        elif v in leave_codes:
            pre_dict_rest[(emp, d)] = v
        elif v in zone_codes:
            pre_dict_work[(emp, d)] = v
        else:
            pre_unknown_lower.append((emp, d, v))

# =========================
#  special_marks（色ベース）を優先して上書き
# =========================
for _, row in df_special.iterrows():
    emp = row["emp_no"]
    d   = row["date"]
    k   = row["kind"]
    if k in SPECIAL_KINDS:
        pre_dict_special[(emp, d)] = k

# =========================
#  デバッグ表示（emp_no→氏名があれば併記）
# =========================
def fmt_key(k):
    emp, d = k
    nm = empno_to_name.get(emp, "")
    if nm:
        return f"{emp}({nm})", d.strftime("%Y-%m-%d")
    return emp, d.strftime("%Y-%m-%d")

def pretty_dict(dct, title):
    print(f"\n■ {title}  count={len(dct)}")
    # 見やすいようにキー整形して表示
    out = {(fmt_key(k)): v for k, v in dct.items()}
    pp.pprint(out)

pretty_dict(pre_dict_rest, "事前指定休暇 (pre_dict_rest)")
pretty_dict(pre_dict_work, "事前指定勤務 (pre_dict_work)")
pretty_dict(pre_dict_special, "事前指定特別業務 (pre_dict_special)")
pretty_dict(pre_dict_time, "事前指定時間帯 (pre_dict_time)")

if pre_unknown_lower:
    print("\n■ 下段の未知コード（入力ミス候補） count=", len(pre_unknown_lower))
    # 先頭だけ表示
    for emp, d, v in pre_unknown_lower[:30]:
        nm = empno_to_name.get(emp, "")
        emp_show = f"{emp}({nm})" if nm else emp
        print(emp_show, d.strftime("%Y-%m-%d"), v)

csv_dir: /Users/hiraokatatsuru/Library/Mobile Documents/com~apple~CloudDocs/postal-operation-shift-management-system/excel_templates/export_csv exists: True
start_date: 2025-11-16 00:00:00
D (28日): DatetimeIndex(['2025-11-16', '2025-11-17', '2025-11-18', '2025-11-19',
               '2025-11-20', '2025-11-21', '2025-11-22', '2025-11-23',
               '2025-11-24', '2025-11-25', '2025-11-26', '2025-11-27',
               '2025-11-28', '2025-11-29', '2025-11-30', '2025-12-01',
               '2025-12-02', '2025-12-03', '2025-12-04', '2025-12-05',
               '2025-12-06', '2025-12-07', '2025-12-08', '2025-12-09',
               '2025-12-10', '2025-12-11', '2025-12-12', '2025-12-13'],
              dtype='datetime64[ns]', freq='D')
df_pre rows (after filtering by D): 11
df_special rows (after filtering by D): 0

■ 事前指定休暇 (pre_dict_rest)  count=10
{('1(社員1_1)', '2025-11-19'): '計年',
 ('10(社員1_10)', '2025-11-29'): '計年',
 ('2(社員1_2)', '2025-12-02'): '計年',
 ('3(社員1_3)', '2025-12-09'): '計年',
 ('4(社員1_4)', '2025-11-26'): '計年',
 ('5(社員1_5)', '2025-11-21'): '計年',
 ('6(社員1_6)', '2025-11-29'): '計年',
 ('7(社員1_7)', '2025-11-29'): '計年',
 ('8(社員1_8)', '2025-12-08'): '計年',
 ('9(社員1_9)', '2025-11-29'): '承欠'}

■ 事前指定勤務 (pre_dict_work)  count=1
{('8(社員1_8)', '2025-11-25'): '速夜'}

■ 事前指定特別業務 (pre_dict_special)  count=0
{}

■ 事前指定時間帯 (pre_dict_time)  count=0
{}

In [80]:
# 1) Python の weekday() から曜日ラベルへのマッピング
weekday_map = {0: '月', 1: '火', 2: '水', 3: '木', 4: '金', 5: '土', 6: '日'}

# 2) 各日付 d∈D を「月～日 or 祝」に変換
date_label = {}
for d in D:
    if jpholiday.is_holiday(d):      # 祝日なら '祝'
        date_label[d] = '祝'
    else:
        date_label[d] = weekday_map[d.weekday()]
#各社員が出勤できる曜日を1、出勤しない(ソルバーが選ばない曜日)を0に設定
# 3) avail[(i,d)] = 1 or 0 の辞書を作成　
#事前指定で出勤しない日に指定が入っていたら1にする
avail = {
    (i, d): 1 if (i, d) in pre_dict_work else C[i][ date_label[d] ]
    for i in C
    for d in D
}

In [81]:
avail

{(1, Timestamp('2025-11-16 00:00:00')): 0,
 (1, Timestamp('2025-11-17 00:00:00')): 1,
 (1, Timestamp('2025-11-18 00:00:00')): 1,
 (1, Timestamp('2025-11-19 00:00:00')): 1,
 (1, Timestamp('2025-11-20 00:00:00')): 1,
 (1, Timestamp('2025-11-21 00:00:00')): 1,
 (1, Timestamp('2025-11-22 00:00:00')): 0,
 (1, Timestamp('2025-11-23 00:00:00')): 0,
 (1, Timestamp('2025-11-24 00:00:00')): 0,
 (1, Timestamp('2025-11-25 00:00:00')): 1,
 (1, Timestamp('2025-11-26 00:00:00')): 1,
 (1, Timestamp('2025-11-27 00:00:00')): 1,
 (1, Timestamp('2025-11-28 00:00:00')): 1,
 (1, Timestamp('2025-11-29 00:00:00')): 0,
 (1, Timestamp('2025-11-30 00:00:00')): 0,
 (1, Timestamp('2025-12-01 00:00:00')): 1,
 (1, Timestamp('2025-12-02 00:00:00')): 1,
 (1, Timestamp('2025-12-03 00:00:00')): 1,
 (1, Timestamp('2025-12-04 00:00:00')): 1,
 (1, Timestamp('2025-12-05 00:00:00')): 1,
 (1, Timestamp('2025-12-06 00:00:00')): 0,
 (1, Timestamp('2025-12-07 00:00:00')): 0,
 (1, Timestamp('2025-12-08 00:00:00')): 1,
 (1, Timestamp('2025-12-09 00:00:00')): 1,
 (1, Timestamp('2025-12-10 00:00:00')): 1,
 (1, Timestamp('2025-12-11 00:00:00')): 1,
 (1, Timestamp('2025-12-12 00:00:00')): 1,
 (1, Timestamp('2025-12-13 00:00:00')): 0,
 (2, Timestamp('2025-11-16 00:00:00')): 1,
 (2, Timestamp('2025-11-17 00:00:00')): 1,
 (2, Timestamp('2025-11-18 00:00:00')): 1,
 (2, Timestamp('2025-11-19 00:00:00')): 1,
 (2, Timestamp('2025-11-20 00:00:00')): 1,
 (2, Timestamp('2025-11-21 00:00:00')): 1,
 (2, Timestamp('2025-11-22 00:00:00')): 1,
 (2, Timestamp('2025-11-23 00:00:00')): 1,
 (2, Timestamp('2025-11-24 00:00:00')): 1,
 (2, Timestamp('2025-11-25 00:00:00')): 1,
 (2, Timestamp('2025-11-26 00:00:00')): 1,
 (2, Timestamp('2025-11-27 00:00:00')): 1,
 (2, Timestamp('2025-11-28 00:00:00')): 1,
 (2, Timestamp('2025-11-29 00:00:00')): 1,
 (2, Timestamp('2025-11-30 00:00:00')): 1,
 (2, Timestamp('2025-12-01 00:00:00')): 1,
 (2, Timestamp('2025-12-02 00:00:00')): 1,
 (2, Timestamp('2025-12-03 00:00:00')): 1,
 (2, Timestamp('2025-12-04 00:00:00')): 1,
 (2, Timestamp('2025-12-05 00:00:00')): 1,
 (2, Timestamp('2025-12-06 00:00:00')): 1,
 (2, Timestamp('2025-12-07 00:00:00')): 1,
 (2, Timestamp('2025-12-08 00:00:00')): 1,
 (2, Timestamp('2025-12-09 00:00:00')): 1,
 (2, Timestamp('2025-12-10 00:00:00')): 1,
 (2, Timestamp('2025-12-11 00:00:00')): 1,
 (2, Timestamp('2025-12-12 00:00:00')): 1,
 (2, Timestamp('2025-12-13 00:00:00')): 1,
 (3, Timestamp('2025-11-16 00:00:00')): 1,
 (3, Timestamp('2025-11-17 00:00:00')): 1,
 (3, Timestamp('2025-11-18 00:00:00')): 1,
 (3, Timestamp('2025-11-19 00:00:00')): 1,
 (3, Timestamp('2025-11-20 00:00:00')): 1,
 (3, Timestamp('2025-11-21 00:00:00')): 1,
 (3, Timestamp('2025-11-22 00:00:00')): 1,
 (3, Timestamp('2025-11-23 00:00:00')): 1,
 (3, Timestamp('2025-11-24 00:00:00')): 1,
 (3, Timestamp('2025-11-25 00:00:00')): 1,
 (3, Timestamp('2025-11-26 00:00:00')): 1,
 (3, Timestamp('2025-11-27 00:00:00')): 1,
 (3, Timestamp('2025-11-28 00:00:00')): 1,
 (3, Timestamp('2025-11-29 00:00:00')): 1,
 (3, Timestamp('2025-11-30 00:00:00')): 1,
 (3, Timestamp('2025-12-01 00:00:00')): 1,
 (3, Timestamp('2025-12-02 00:00:00')): 1,
 (3, Timestamp('2025-12-03 00:00:00')): 1,
 (3, Timestamp('2025-12-04 00:00:00')): 1,
 (3, Timestamp('2025-12-05 00:00:00')): 1,
 (3, Timestamp('2025-12-06 00:00:00')): 1,
 (3, Timestamp('2025-12-07 00:00:00')): 1,
 (3, Timestamp('2025-12-08 00:00:00')): 1,
 (3, Timestamp('2025-12-09 00:00:00')): 1,
 (3, Timestamp('2025-12-10 00:00:00')): 1,
 (3, Timestamp('2025-12-11 00:00:00')): 1,
 (3, Timestamp('2025-12-12 00:00:00')): 1,
 (3, Timestamp('2025-12-13 00:00:00')): 1,
 (4, Timestamp('2025-11-16 00:00:00')): 1,
 (4, Timestamp('2025-11-17 00:00:00')): 1,
 (4, Timestamp('2025-11-18 00:00:00')): 1,
 (4, Timestamp('2025-11-19 00:00:00')): 1,
 (4, Timestamp('2025-11-20 00:00:00')): 1,
 (4, Timestamp('2025-11-21 00:00:00')): 1,
 (4, Timestamp('2025-11-22 00:00:00')): 1,
 (4, Timestamp('2025-11-23 00:00:00')): 1,
 (4, Timestamp('2025-11-24 00:00:00')): 1,
 (4, Timestamp('2025-11-25 00:00:00')): 1,
 (4, Timestamp('2025-11-26 00:00:00')): 1,
 (4, Timestamp('2025-11-27 00:00:00')): 1,
 (4, Timestamp('2025-11-28 00:00:00')): 1,
 (4, Timestamp('2025-11-29 00:00:00')): 1,
 (4, Timestamp('2025-11-30 00:00:00')): 1,
 (4, Timestamp('2025-12-01 00:00:00')): 1,
 (4, Timestamp('2025-12-02 00:00:00')): 1,
 (4, Timestamp('2025-12-03 00:00:00')): 1,
 (4, Timestamp('2025-12-04 00:00:00')): 1,
 (4, Timestamp('2025-12-05 00:00:00')): 1,
 (4, Timestamp('2025-12-06 00:00:00')): 1,
 (4, Timestamp('2025-12-07 00:00:00')): 1,
 (4, Timestamp('2025-12-08 00:00:00')): 1,
 (4, Timestamp('2025-12-09 00:00:00')): 1,
 (4, Timestamp('2025-12-10 00:00:00')): 1,
 (4, Timestamp('2025-12-11 00:00:00')): 1,
 (4, Timestamp('2025-12-12 00:00:00')): 1,
 (4, Timestamp('2025-12-13 00:00:00')): 1,
 (5, Timestamp('2025-11-16 00:00:00')): 1,
 (5, Timestamp('2025-11-17 00:00:00')): 1,
 (5, Timestamp('2025-11-18 00:00:00')): 1,
 (5, Timestamp('2025-11-19 00:00:00')): 1,
 (5, Timestamp('2025-11-20 00:00:00')): 1,
 (5, Timestamp('2025-11-21 00:00:00')): 1,
 (5, Timestamp('2025-11-22 00:00:00')): 1,
 (5, Timestamp('2025-11-23 00:00:00')): 1,
 (5, Timestamp('2025-11-24 00:00:00')): 1,
 (5, Timestamp('2025-11-25 00:00:00')): 1,
 (5, Timestamp('2025-11-26 00:00:00')): 1,
 (5, Timestamp('2025-11-27 00:00:00')): 1,
 (5, Timestamp('2025-11-28 00:00:00')): 1,
 (5, Timestamp('2025-11-29 00:00:00')): 1,
 (5, Timestamp('2025-11-30 00:00:00')): 1,
 (5, Timestamp('2025-12-01 00:00:00')): 1,
 (5, Timestamp('2025-12-02 00:00:00')): 1,
 (5, Timestamp('2025-12-03 00:00:00')): 1,
 (5, Timestamp('2025-12-04 00:00:00')): 1,
 (5, Timestamp('2025-12-05 00:00:00')): 1,
 (5, Timestamp('2025-12-06 00:00:00')): 1,
 (5, Timestamp('2025-12-07 00:00:00')): 1,
 (5, Timestamp('2025-12-08 00:00:00')): 1,
 (5, Timestamp('2025-12-09 00:00:00')): 1,
 (5, Timestamp('2025-12-10 00:00:00')): 1,
 (5, Timestamp('2025-12-11 00:00:00')): 1,
 (5, Timestamp('2025-12-12 00:00:00')): 1,
 (5, Timestamp('2025-12-13 00:00:00')): 1,
 (6, Timestamp('2025-11-16 00:00:00')): 0,
 (6, Timestamp('2025-11-17 00:00:00')): 1,
 (6, Timestamp('2025-11-18 00:00:00')): 1,
 (6, Timestamp('2025-11-19 00:00:00')): 1,
 (6, Timestamp('2025-11-20 00:00:00')): 1,
 (6, Timestamp('2025-11-21 00:00:00')): 1,
 (6, Timestamp('2025-11-22 00:00:00')): 0,
 (6, Timestamp('2025-11-23 00:00:00')): 0,
 (6, Timestamp('2025-11-24 00:00:00')): 0,
 (6, Timestamp('2025-11-25 00:00:00')): 1,
 (6, Timestamp('2025-11-26 00:00:00')): 1,
 (6, Timestamp('2025-11-27 00:00:00')): 1,
 (6, Timestamp('2025-11-28 00:00:00')): 1,
 (6, Timestamp('2025-11-29 00:00:00')): 0,
 (6, Timestamp('2025-11-30 00:00:00')): 0,
 (6, Timestamp('2025-12-01 00:00:00')): 1,
 (6, Timestamp('2025-12-02 00:00:00')): 1,
 (6, Timestamp('2025-12-03 00:00:00')): 1,
 (6, Timestamp('2025-12-04 00:00:00')): 1,
 (6, Timestamp('2025-12-05 00:00:00')): 1,
 (6, Timestamp('2025-12-06 00:00:00')): 0,
 (6, Timestamp('2025-12-07 00:00:00')): 0,
 (6, Timestamp('2025-12-08 00:00:00')): 1,
 (6, Timestamp('2025-12-09 00:00:00')): 1,
 (6, Timestamp('2025-12-10 00:00:00')): 1,
 (6, Timestamp('2025-12-11 00:00:00')): 1,
 (6, Timestamp('2025-12-12 00:00:00')): 1,
 (6, Timestamp('2025-12-13 00:00:00')): 0,
 (7, Timestamp('2025-11-16 00:00:00')): 0,
 (7, Timestamp('2025-11-17 00:00:00')): 1,
 (7, Timestamp('2025-11-18 00:00:00')): 1,
 (7, Timestamp('2025-11-19 00:00:00')): 1,
 (7, Timestamp('2025-11-20 00:00:00')): 1,
 (7, Timestamp('2025-11-21 00:00:00')): 1,
 (7, Timestamp('2025-11-22 00:00:00')): 0,
 (7, Timestamp('2025-11-23 00:00:00')): 0,
 (7, Timestamp('2025-11-24 00:00:00')): 0,
 (7, Timestamp('2025-11-25 00:00:00')): 1,
 (7, Timestamp('2025-11-26 00:00:00')): 1,
 (7, Timestamp('2025-11-27 00:00:00')): 1,
 (7, Timestamp('2025-11-28 00:00:00')): 1,
 (7, Timestamp('2025-11-29 00:00:00')): 0,
 (7, Timestamp('2025-11-30 00:00:00')): 0,
 (7, Timestamp('2025-12-01 00:00:00')): 1,
 (7, Timestamp('2025-12-02 00:00:00')): 1,
 (7, Timestamp('2025-12-03 00:00:00')): 1,
 (7, Timestamp('2025-12-04 00:00:00')): 1,
 (7, Timestamp('2025-12-05 00:00:00')): 1,
 (7, Timestamp('2025-12-06 00:00:00')): 0,
 (7, Timestamp('2025-12-07 00:00:00')): 0,
 (7, Timestamp('2025-12-08 00:00:00')): 1,
 (7, Timestamp('2025-12-09 00:00:00')): 1,
 (7, Timestamp('2025-12-10 00:00:00')): 1,
 (7, Timestamp('2025-12-11 00:00:00')): 1,
 (7, Timestamp('2025-12-12 00:00:00')): 1,
 (7, Timestamp('2025-12-13 00:00:00')): 0,
 (8, Timestamp('2025-11-16 00:00:00')): 0,
 (8, Timestamp('2025-11-17 00:00:00')): 1,
 (8, Timestamp('2025-11-18 00:00:00')): 0,
 (8, Timestamp('2025-11-19 00:00:00')): 0,
 (8, Timestamp('2025-11-20 00:00:00')): 1,
 (8, Timestamp('2025-11-21 00:00:00')): 1,
 (8, Timestamp('2025-11-22 00:00:00')): 0,
 (8, Timestamp('2025-11-23 00:00:00')): 0,
 (8, Timestamp('2025-11-24 00:00:00')): 0,
 (8, Timestamp('2025-11-25 00:00:00')): 0,
 (8, Timestamp('2025-11-26 00:00:00')): 0,
 (8, Timestamp('2025-11-27 00:00:00')): 1,
 (8, Timestamp('2025-11-28 00:00:00')): 1,
 (8, Timestamp('2025-11-29 00:00:00')): 0,
 (8, Timestamp('2025-11-30 00:00:00')): 0,
 (8, Timestamp('2025-12-01 00:00:00')): 1,
 (8, Timestamp('2025-12-02 00:00:00')): 0,
 (8, Timestamp('2025-12-03 00:00:00')): 0,
 (8, Timestamp('2025-12-04 00:00:00')): 1,
 (8, Timestamp('2025-12-05 00:00:00')): 1,
 (8, Timestamp('2025-12-06 00:00:00')): 0,
 (8, Timestamp('2025-12-07 00:00:00')): 0,
 (8, Timestamp('2025-12-08 00:00:00')): 1,
 (8, Timestamp('2025-12-09 00:00:00')): 0,
 (8, Timestamp('2025-12-10 00:00:00')): 0,
 (8, Timestamp('2025-12-11 00:00:00')): 1,
 (8, Timestamp('2025-12-12 00:00:00')): 1,
 (8, Timestamp('2025-12-13 00:00:00')): 0,
 (9, Timestamp('2025-11-16 00:00:00')): 0,
 (9, Timestamp('2025-11-17 00:00:00')): 1,
 (9, Timestamp('2025-11-18 00:00:00')): 1,
 (9, Timestamp('2025-11-19 00:00:00')): 1,
 (9, Timestamp('2025-11-20 00:00:00')): 1,
 (9, Timestamp('2025-11-21 00:00:00')): 1,
 (9, Timestamp('2025-11-22 00:00:00')): 0,
 (9, Timestamp('2025-11-23 00:00:00')): 0,
 (9, Timestamp('2025-11-24 00:00:00')): 0,
 (9, Timestamp('2025-11-25 00:00:00')): 1,
 (9, Timestamp('2025-11-26 00:00:00')): 1,
 (9, Timestamp('2025-11-27 00:00:00')): 1,
 (9, Timestamp('2025-11-28 00:00:00')): 1,
 (9, Timestamp('2025-11-29 00:00:00')): 0,
 (9, Timestamp('2025-11-30 00:00:00')): 0,
 (9, Timestamp('2025-12-01 00:00:00')): 1,
 (9, Timestamp('2025-12-02 00:00:00')): 1,
 (9, Timestamp('2025-12-03 00:00:00')): 1,
 (9, Timestamp('2025-12-04 00:00:00')): 1,
 (9, Timestamp('2025-12-05 00:00:00')): 1,
 (9, Timestamp('2025-12-06 00:00:00')): 0,
 (9, Timestamp('2025-12-07 00:00:00')): 0,
 (9, Timestamp('2025-12-08 00:00:00')): 1,
 (9, Timestamp('2025-12-09 00:00:00')): 1,
 (9, Timestamp('2025-12-10 00:00:00')): 1,
 (9, Timestamp('2025-12-11 00:00:00')): 1,
 (9, Timestamp('2025-12-12 00:00:00')): 1,
 (9, Timestamp('2025-12-13 00:00:00')): 0,
 (10, Timestamp('2025-11-16 00:00:00')): 0,
 (10, Timestamp('2025-11-17 00:00:00')): 1,
 (10, Timestamp('2025-11-18 00:00:00')): 1,
 (10, Timestamp('2025-11-19 00:00:00')): 1,
 (10, Timestamp('2025-11-20 00:00:00')): 1,
 (10, Timestamp('2025-11-21 00:00:00')): 1,
 (10, Timestamp('2025-11-22 00:00:00')): 0,
 (10, Timestamp('2025-11-23 00:00:00')): 0,
 (10, Timestamp('2025-11-24 00:00:00')): 0,
 (10, Timestamp('2025-11-25 00:00:00')): 1,
 (10, Timestamp('2025-11-26 00:00:00')): 1,
 (10, Timestamp('2025-11-27 00:00:00')): 1,
 (10, Timestamp('2025-11-28 00:00:00')): 1,
 (10, Timestamp('2025-11-29 00:00:00')): 0,
 (10, Timestamp('2025-11-30 00:00:00')): 0,
 (10, Timestamp('2025-12-01 00:00:00')): 1,
 (10, Timestamp('2025-12-02 00:00:00')): 1,
 (10, Timestamp('2025-12-03 00:00:00')): 1,
 (10, Timestamp('2025-12-04 00:00:00')): 1,
 (10, Timestamp('2025-12-05 00:00:00')): 1,
 (10, Timestamp('2025-12-06 00:00:00')): 0,
 (10, Timestamp('2025-12-07 00:00:00')): 0,
 (10, Timestamp('2025-12-08 00:00:00')): 1,
 (10, Timestamp('2025-12-09 00:00:00')): 1,
 (10, Timestamp('2025-12-10 00:00:00')): 1,
 (10, Timestamp('2025-12-11 00:00:00')): 1,
 (10, Timestamp('2025-12-12 00:00:00')): 1,
 (10, Timestamp('2025-12-13 00:00:00')): 0}

In [118]:
def is_newyear_3days(d: pd.Timestamp) -> bool:
    # 例：1/1〜1/3
    return (d.month == 1 and d.day in (1, 2, 3))

def label_for_req(d: pd.Timestamp) -> str:
    wd = d.weekday()  # 0=月…6=日

    # 1) 正月3日間は祝日扱い（最優先）
    if is_newyear_3days(d):
        return "祝"

    # 2) 日曜は普通の日曜扱い（祝日より優先）
    if wd == 6:
        return "日"

    # 3) それ以外の祝日
    if jpholiday.is_holiday(d.date()):
        return "祝"

    # 4) 平日/土
    if wd < 5:
        return ["月", "火", "水", "木", "金"][wd]
    return "土"

In [119]:
req = {}
for d in D:
    label = label_for_req(d)
    for k in mapping.get(label, []):
        req[(d, k)] = 1

In [120]:
req

{(Timestamp('2025-11-16 00:00:00'), '速早'): 1,
 (Timestamp('2025-11-16 00:00:00'), '速夜(日)'): 1,
 (Timestamp('2025-11-17 00:00:00'), '1区'): 1,
 (Timestamp('2025-11-17 00:00:00'), '2区'): 1,
 (Timestamp('2025-11-17 00:00:00'), '3区'): 1,
 (Timestamp('2025-11-17 00:00:00'), '4区'): 1,
 (Timestamp('2025-11-17 00:00:00'), '大口1'): 1,
 (Timestamp('2025-11-17 00:00:00'), '大口1-3'): 1,
 (Timestamp('2025-11-17 00:00:00'), '補助'): 1,
 (Timestamp('2025-11-17 00:00:00'), '速夜'): 1,
 (Timestamp('2025-11-17 00:00:00'), '組立'): 1,
 (Timestamp('2025-11-18 00:00:00'), '1区'): 1,
 (Timestamp('2025-11-18 00:00:00'), '2区'): 1,
 (Timestamp('2025-11-18 00:00:00'), '3区'): 1,
 (Timestamp('2025-11-18 00:00:00'), '4区'): 1,
 (Timestamp('2025-11-18 00:00:00'), '大口1'): 1,
 (Timestamp('2025-11-18 00:00:00'), '大口1-3'): 1,
 (Timestamp('2025-11-18 00:00:00'), '補助'): 1,
 (Timestamp('2025-11-18 00:00:00'), '速夜'): 1,
 (Timestamp('2025-11-18 00:00:00'), '組立'): 1,
 (Timestamp('2025-11-19 00:00:00'), '1区'): 1,
 (Timestamp('2025-11-19 00:00:00'), '2区'): 1,
 (Timestamp('2025-11-19 00:00:00'), '3区'): 1,
 (Timestamp('2025-11-19 00:00:00'), '4区'): 1,
 (Timestamp('2025-11-19 00:00:00'), '大口1'): 1,
 (Timestamp('2025-11-19 00:00:00'), '大口1-3'): 1,
 (Timestamp('2025-11-19 00:00:00'), '補助'): 1,
 (Timestamp('2025-11-19 00:00:00'), '速夜'): 1,
 (Timestamp('2025-11-19 00:00:00'), '組立'): 1,
 (Timestamp('2025-11-20 00:00:00'), '1区'): 1,
 (Timestamp('2025-11-20 00:00:00'), '2区'): 1,
 (Timestamp('2025-11-20 00:00:00'), '3区'): 1,
 (Timestamp('2025-11-20 00:00:00'), '4区'): 1,
 (Timestamp('2025-11-20 00:00:00'), '大口1'): 1,
 (Timestamp('2025-11-20 00:00:00'), '大口1-3'): 1,
 (Timestamp('2025-11-20 00:00:00'), '補助'): 1,
 (Timestamp('2025-11-20 00:00:00'), '速夜'): 1,
 (Timestamp('2025-11-20 00:00:00'), '組立'): 1,
 (Timestamp('2025-11-21 00:00:00'), '1区'): 1,
 (Timestamp('2025-11-21 00:00:00'), '2区'): 1,
 (Timestamp('2025-11-21 00:00:00'), '3区'): 1,
 (Timestamp('2025-11-21 00:00:00'), '4区'): 1,
 (Timestamp('2025-11-21 00:00:00'), '大口1'): 1,
 (Timestamp('2025-11-21 00:00:00'), '大口1-3'): 1,
 (Timestamp('2025-11-21 00:00:00'), '補助'): 1,
 (Timestamp('2025-11-21 00:00:00'), '速夜'): 1,
 (Timestamp('2025-11-21 00:00:00'), '組立'): 1,
 (Timestamp('2025-11-22 00:00:00'), '補助'): 1,
 (Timestamp('2025-11-22 00:00:00'), '速早'): 1,
 (Timestamp('2025-11-22 00:00:00'), '速夜(土)'): 1,
 (Timestamp('2025-11-23 00:00:00'), '速早'): 1,
 (Timestamp('2025-11-23 00:00:00'), '速夜(日)'): 1,
 (Timestamp('2025-11-24 00:00:00'), '補助'): 1,
 (Timestamp('2025-11-24 00:00:00'), '速早'): 1,
 (Timestamp('2025-11-24 00:00:00'), '速夜(祝)'): 1,
 (Timestamp('2025-11-25 00:00:00'), '1区'): 1,
 (Timestamp('2025-11-25 00:00:00'), '2区'): 1,
 (Timestamp('2025-11-25 00:00:00'), '3区'): 1,
 (Timestamp('2025-11-25 00:00:00'), '4区'): 1,
 (Timestamp('2025-11-25 00:00:00'), '大口1'): 1,
 (Timestamp('2025-11-25 00:00:00'), '大口1-3'): 1,
 (Timestamp('2025-11-25 00:00:00'), '補助'): 1,
 (Timestamp('2025-11-25 00:00:00'), '速夜'): 1,
 (Timestamp('2025-11-25 00:00:00'), '組立'): 1,
 (Timestamp('2025-11-26 00:00:00'), '1区'): 1,
 (Timestamp('2025-11-26 00:00:00'), '2区'): 1,
 (Timestamp('2025-11-26 00:00:00'), '3区'): 1,
 (Timestamp('2025-11-26 00:00:00'), '4区'): 1,
 (Timestamp('2025-11-26 00:00:00'), '大口1'): 1,
 (Timestamp('2025-11-26 00:00:00'), '大口1-3'): 1,
 (Timestamp('2025-11-26 00:00:00'), '補助'): 1,
 (Timestamp('2025-11-26 00:00:00'), '速夜'): 1,
 (Timestamp('2025-11-26 00:00:00'), '組立'): 1,
 (Timestamp('2025-11-27 00:00:00'), '1区'): 1,
 (Timestamp('2025-11-27 00:00:00'), '2区'): 1,
 (Timestamp('2025-11-27 00:00:00'), '3区'): 1,
 (Timestamp('2025-11-27 00:00:00'), '4区'): 1,
 (Timestamp('2025-11-27 00:00:00'), '大口1'): 1,
 (Timestamp('2025-11-27 00:00:00'), '大口1-3'): 1,
 (Timestamp('2025-11-27 00:00:00'), '補助'): 1,
 (Timestamp('2025-11-27 00:00:00'), '速夜'): 1,
 (Timestamp('2025-11-27 00:00:00'), '組立'): 1,
 (Timestamp('2025-11-28 00:00:00'), '1区'): 1,
 (Timestamp('2025-11-28 00:00:00'), '2区'): 1,
 (Timestamp('2025-11-28 00:00:00'), '3区'): 1,
 (Timestamp('2025-11-28 00:00:00'), '4区'): 1,
 (Timestamp('2025-11-28 00:00:00'), '大口1'): 1,
 (Timestamp('2025-11-28 00:00:00'), '大口1-3'): 1,
 (Timestamp('2025-11-28 00:00:00'), '補助'): 1,
 (Timestamp('2025-11-28 00:00:00'), '速夜'): 1,
 (Timestamp('2025-11-28 00:00:00'), '組立'): 1,
 (Timestamp('2025-11-29 00:00:00'), '補助'): 1,
 (Timestamp('2025-11-29 00:00:00'), '速早'): 1,
 (Timestamp('2025-11-29 00:00:00'), '速夜(土)'): 1,
 (Timestamp('2025-11-30 00:00:00'), '速早'): 1,
 (Timestamp('2025-11-30 00:00:00'), '速夜(日)'): 1,
 (Timestamp('2025-12-01 00:00:00'), '1区'): 1,
 (Timestamp('2025-12-01 00:00:00'), '2区'): 1,
 (Timestamp('2025-12-01 00:00:00'), '3区'): 1,
 (Timestamp('2025-12-01 00:00:00'), '4区'): 1,
 (Timestamp('2025-12-01 00:00:00'), '大口1'): 1,
 (Timestamp('2025-12-01 00:00:00'), '大口1-3'): 1,
 (Timestamp('2025-12-01 00:00:00'), '補助'): 1,
 (Timestamp('2025-12-01 00:00:00'), '速夜'): 1,
 (Timestamp('2025-12-01 00:00:00'), '組立'): 1,
 (Timestamp('2025-12-02 00:00:00'), '1区'): 1,
 (Timestamp('2025-12-02 00:00:00'), '2区'): 1,
 (Timestamp('2025-12-02 00:00:00'), '3区'): 1,
 (Timestamp('2025-12-02 00:00:00'), '4区'): 1,
 (Timestamp('2025-12-02 00:00:00'), '大口1'): 1,
 (Timestamp('2025-12-02 00:00:00'), '大口1-3'): 1,
 (Timestamp('2025-12-02 00:00:00'), '補助'): 1,
 (Timestamp('2025-12-02 00:00:00'), '速夜'): 1,
 (Timestamp('2025-12-02 00:00:00'), '組立'): 1,
 (Timestamp('2025-12-03 00:00:00'), '1区'): 1,
 (Timestamp('2025-12-03 00:00:00'), '2区'): 1,
 (Timestamp('2025-12-03 00:00:00'), '3区'): 1,
 (Timestamp('2025-12-03 00:00:00'), '4区'): 1,
 (Timestamp('2025-12-03 00:00:00'), '大口1'): 1,
 (Timestamp('2025-12-03 00:00:00'), '大口1-3'): 1,
 (Timestamp('2025-12-03 00:00:00'), '補助'): 1,
 (Timestamp('2025-12-03 00:00:00'), '速夜'): 1,
 (Timestamp('2025-12-03 00:00:00'), '組立'): 1,
 (Timestamp('2025-12-04 00:00:00'), '1区'): 1,
 (Timestamp('2025-12-04 00:00:00'), '2区'): 1,
 (Timestamp('2025-12-04 00:00:00'), '3区'): 1,
 (Timestamp('2025-12-04 00:00:00'), '4区'): 1,
 (Timestamp('2025-12-04 00:00:00'), '大口1'): 1,
 (Timestamp('2025-12-04 00:00:00'), '大口1-3'): 1,
 (Timestamp('2025-12-04 00:00:00'), '補助'): 1,
 (Timestamp('2025-12-04 00:00:00'), '速夜'): 1,
 (Timestamp('2025-12-04 00:00:00'), '組立'): 1,
 (Timestamp('2025-12-05 00:00:00'), '1区'): 1,
 (Timestamp('2025-12-05 00:00:00'), '2区'): 1,
 (Timestamp('2025-12-05 00:00:00'), '3区'): 1,
 (Timestamp('2025-12-05 00:00:00'), '4区'): 1,
 (Timestamp('2025-12-05 00:00:00'), '大口1'): 1,
 (Timestamp('2025-12-05 00:00:00'), '大口1-3'): 1,
 (Timestamp('2025-12-05 00:00:00'), '補助'): 1,
 (Timestamp('2025-12-05 00:00:00'), '速夜'): 1,
 (Timestamp('2025-12-05 00:00:00'), '組立'): 1,
 (Timestamp('2025-12-06 00:00:00'), '補助'): 1,
 (Timestamp('2025-12-06 00:00:00'), '速早'): 1,
 (Timestamp('2025-12-06 00:00:00'), '速夜(土)'): 1,
 (Timestamp('2025-12-07 00:00:00'), '速早'): 1,
 (Timestamp('2025-12-07 00:00:00'), '速夜(日)'): 1,
 (Timestamp('2025-12-08 00:00:00'), '1区'): 1,
 (Timestamp('2025-12-08 00:00:00'), '2区'): 1,
 (Timestamp('2025-12-08 00:00:00'), '3区'): 1,
 (Timestamp('2025-12-08 00:00:00'), '4区'): 1,
 (Timestamp('2025-12-08 00:00:00'), '大口1'): 1,
 (Timestamp('2025-12-08 00:00:00'), '大口1-3'): 1,
 (Timestamp('2025-12-08 00:00:00'), '補助'): 1,
 (Timestamp('2025-12-08 00:00:00'), '速夜'): 1,
 (Timestamp('2025-12-08 00:00:00'), '組立'): 1,
 (Timestamp('2025-12-09 00:00:00'), '1区'): 1,
 (Timestamp('2025-12-09 00:00:00'), '2区'): 1,
 (Timestamp('2025-12-09 00:00:00'), '3区'): 1,
 (Timestamp('2025-12-09 00:00:00'), '4区'): 1,
 (Timestamp('2025-12-09 00:00:00'), '大口1'): 1,
 (Timestamp('2025-12-09 00:00:00'), '大口1-3'): 1,
 (Timestamp('2025-12-09 00:00:00'), '補助'): 1,
 (Timestamp('2025-12-09 00:00:00'), '速夜'): 1,
 (Timestamp('2025-12-09 00:00:00'), '組立'): 1,
 (Timestamp('2025-12-10 00:00:00'), '1区'): 1,
 (Timestamp('2025-12-10 00:00:00'), '2区'): 1,
 (Timestamp('2025-12-10 00:00:00'), '3区'): 1,
 (Timestamp('2025-12-10 00:00:00'), '4区'): 1,
 (Timestamp('2025-12-10 00:00:00'), '大口1'): 1,
 (Timestamp('2025-12-10 00:00:00'), '大口1-3'): 1,
 (Timestamp('2025-12-10 00:00:00'), '補助'): 1,
 (Timestamp('2025-12-10 00:00:00'), '速夜'): 1,
 (Timestamp('2025-12-10 00:00:00'), '組立'): 1,
 (Timestamp('2025-12-11 00:00:00'), '1区'): 1,
 (Timestamp('2025-12-11 00:00:00'), '2区'): 1,
 (Timestamp('2025-12-11 00:00:00'), '3区'): 1,
 (Timestamp('2025-12-11 00:00:00'), '4区'): 1,
 (Timestamp('2025-12-11 00:00:00'), '大口1'): 1,
 (Timestamp('2025-12-11 00:00:00'), '大口1-3'): 1,
 (Timestamp('2025-12-11 00:00:00'), '補助'): 1,
 (Timestamp('2025-12-11 00:00:00'), '速夜'): 1,
 (Timestamp('2025-12-11 00:00:00'), '組立'): 1,
 (Timestamp('2025-12-12 00:00:00'), '1区'): 1,
 (Timestamp('2025-12-12 00:00:00'), '2区'): 1,
 (Timestamp('2025-12-12 00:00:00'), '3区'): 1,
 (Timestamp('2025-12-12 00:00:00'), '4区'): 1,
 (Timestamp('2025-12-12 00:00:00'), '大口1'): 1,
 (Timestamp('2025-12-12 00:00:00'), '大口1-3'): 1,
 (Timestamp('2025-12-12 00:00:00'), '補助'): 1,
 (Timestamp('2025-12-12 00:00:00'), '速夜'): 1,
 (Timestamp('2025-12-12 00:00:00'), '組立'): 1,
 (Timestamp('2025-12-13 00:00:00'), '補助'): 1,
 (Timestamp('2025-12-13 00:00:00'), '速早'): 1,
 (Timestamp('2025-12-13 00:00:00'), '速夜(土)'): 1}

In [84]:
import pulp

In [85]:
#数理モデルのインスタンス作成
model = pulp.LpProblem("Shift_Scheduling", pulp.LpMinimize)

In [86]:
# バイナリ変数の定義
x = pulp.LpVariable.dicts(
    "Shift",
    [
        (i, d, k)
        for i in I
        for d in D
        for k in K
    ],
    cat='Binary'
)

In [87]:
# 補助変数 y[i,d] = 1 なら社員iが日にちdに勤務
y = pulp.LpVariable.dicts(
    "WorkDay",
    [(i, d) for i in I for d in D],
    cat='Binary'
)

In [88]:
# 休みタイプ変数 rest[i,d,r]　必要
rest = pulp.LpVariable.dicts(
    "Rest",
    [(i, d, r) for i in I for d in D for r in R],
    cat='Binary'
)

In [89]:
specialWork = pulp.LpVariable.dicts(
    "X_Special",
    [
        (i,d,s)
        for i in I
        for d in D
        for s in special_attendance  # (廃休 or マル超)
    ],
    cat=pulp.LpBinary
)

In [90]:
#欠区の定義
# missing=1 なら (d,t,k) は欠区（割り当て0人）
# missing=0 なら 需要をフルに満たす
missing = pulp.LpVariable.dicts(
    "Missing",
    [(d,k) for (d,k) in req.keys()],
    cat='Binary'
)

In [91]:
#連勤を判定するための補助変数
normal_work = pulp.LpVariable.dicts(
    "NormalWork",
    [(i,d) for i in I for d in D],
    cat=pulp.LpBinary
)

In [92]:
#曜日による出勤の指定
#事前指定より先に実行して、事前指定があれば上書きされるようにする
for i in I:
    for d in D:
        for k in K:
            # avail[(i,d)] が 0(出勤しない曜日) のとき x[(i,d,k)] == 0
            model += x[(i, d, k)] <= avail[(i, d)], f"Avail_{i}_{d}_{k}"

In [93]:
# ---------- 休暇の事前指定 ----------
for i in I:
    for d in D:
        # ----- 休暇指定がある場合 (事前指定で休暇にする日) -----
        if (i, d) in pre_dict_rest:
            rest_type = pre_dict_rest[(i, d)]
            model += rest[(i, d, rest_type)] == 1, f"Rest_{i}_{d}_{rest_type}"
           # 他の通常休暇は0
            for r_ in R:
                if r_ != rest_type:
                    model += rest[(i, d, r_)] == 0, f"RestZero_{i}_{d}_{r_}" 

            # 休暇指定の日は勤務しない → x=0, specialWork=0
            for k in K:
                model += x[(i, d, k)] == 0, f"ZeroX_{i}_{d}_{k}"
                
            # 特別状態(廃休,マル超) も0
            for s in special_attendance:
                model += specialWork[(i, d, s)] == 0, f"ZeroSpWork_{i}_{d}_{s}"

        else:
            # ----- 休暇指定がない → 勤務の事前指定をチェック ----
            # 休暇指定がない
            # ソルバーに選ばせたくない休暇 (例: "計年","夏休"...) は 0固定
            # 逆に "週休","非番","祝休"などはソルバーが使うかもしれない(要件次第)
            for r in R:
                if r not in ["週休", "非番", "祝休"]:
                    model += rest[(i, d, r)] == 0, f"ZeroRest_{i}_{d}_{r}"

In [94]:
#"""廃休、マル超の事前指定"""
for i in I:
    for d in D:
        if (i, d) in pre_dict_special:
            s_type = pre_dict_special[(i, d)]
            for s in special_attendance:
                if s == s_type:
                    model += specialWork[(i, d, s)] == 1, f"FixSpec_{i}_{d}_{s}"
                else:
                    model += specialWork[(i, d, s)] == 0, f"ZeroSpec_{i}_{d}_{s}"

        else:
            # 特別状態の指定なし -> 全0
            for s in special_attendance:
                model += specialWork[(i, d, s)] == 0, f"NoSpec_{i}_{d}_{s}"

In [95]:
#"""業務の事前指定"""
for i in I:
    for d in D:
        for k in K:
            # もし (i, d) が pre_dict_work にあって、
            # その値がこの k なら x[(i,d,k)] == 1
            if pre_dict_work.get((i, d)) == k:
                model += x[(i, d, k)] == 1, f"ForceWork_{i}_{d}_{k}"
            else:
                # req に無いなら 0 固定
                if (d, k) not in req:
                    model += x[(i, d, k)] == 0, f"NoReq_{i}_{d}_{k}"
                else:
                    # それ以外はソルバー自由
                    pass

In [96]:
# 各社員が各日にちに勤務(y[i,d])するか、休暇(rest[i,d,r])を取るか、
for i in I:
    for d in D:
        model += (
            y[i, d]
            + pulp.lpSum(rest[i, d, r] for r in R)
        ) == 1, f"WorkOrRest_{i}_{d}"

In [97]:
#"""１日に入れるのは１シフトのみ"""
for i in I:
    for d in D:
        # シフト×業務 の合計
        sum_x_id = pulp.lpSum(x[(i, d, k)] for k in K)

        # 1) 勤務するなら sum_x_id = 1
        # 2) 勤務しない(=0)なら sum_x_id = 0
        #  → sum_x_id == y[i,d]　1日出勤フラグの紐付け(重要)
        model += sum_x_id == y[(i,d)], f"OneShiftOrNone_{i}_{d}"

In [98]:
for i in I:
    for d in D:
        for k in K:
            # 1) A に含まれる業務なら、ソルバー自由
            #    ただし (i,d) に対する事前指定がこの k なら強制 x=1
            if k in A[i]:
                if pre_dict_work.get((i, d)) == k:
                    model += x[(i, d, k)] == 1, f"MustWork_{i}_{d}_{k}"
                else:
                    # ソルバー自由 => 制約は書かない
                    pass

            # 2) B に含まれる業務なら、事前指定がこの k なら x=1、されていなければ x=0
            elif k in B[i]:
                if pre_dict_work.get((i, d)) == k:
                    model += x[(i, d, k)] == 1, f"MustWork_{i}_{d}_{k}"
                else:
                    model += x[(i, d, k)] == 0, f"NoWork_{i}_{d}_{k}"

            # 3) どちらにもない業務は担当不可
            else:
                model += x[(i, d, k)] == 0, f"InvalidJob_{i}_{d}_{k}"

In [99]:
for i in I:
    for d in D:
        # 週休 + 廃休 <= 1
        model += rest[(i,d,'週休')] + specialWork[(i,d,'廃休')] <= 1
        # 非番 + マル超 <= 1
        model += rest[(i,d,'非番')] + specialWork[(i,d,'マル超')] <= 1

In [100]:
for i in I:
    # 週休は月に4日
    model += (
        pulp.lpSum(
            rest[(i,d,'週休')] + specialWork[(i,d,'廃休')]
            for d in D
        ) == 4
    ), f"WeeklyOff_{i}"

    # 非番は4日以上
    model += (
        pulp.lpSum(
            rest[(i,d,'非番')] + specialWork[(i,d,'マル超')]
            for d in D
        ) >= 4
    ), f"Hiban_{i}"

In [101]:
#週に1回週休をとる(廃休をとってもカウントされる)
for i in I:
    for w, days_in_week in enumerate(W):
        #rest(週休) + x_special(廃休) == 1
        model += (
            pulp.lpSum(rest[(i,d,'週休')] + specialWork[(i,d,'廃休')]
                        for d in days_in_week) == 1
        )

In [102]:
#スラック変数
devPos = {}
devNeg = {}

In [103]:
#なるべく週に１回非番をとるがとれない場合はスラック変数により別の週にとることも可
for i in I:
    for w, days_in_week in enumerate(W):
        # 週の "(非番 + マル超)" 回数
        sumHibanOrMarucho = pulp.lpSum(
            rest[(i,d,'非番')] + specialWork[(i,d,'マル超')]
            for d in days_in_week
        )
        
        # スラック変数
        devPos[(i,w)] = pulp.LpVariable(f"devPos_{i}_{w}", lowBound=0)
        devNeg[(i,w)] = pulp.LpVariable(f"devNeg_{i}_{w}", lowBound=0)
        
        model += sumHibanOrMarucho - 1 <= devPos[(i,w)]
        model += 1 - sumHibanOrMarucho <= devNeg[(i,w)]

In [104]:
#日曜日に休む場合は週休
for i in I:
    for d in D_sunday:
        model += y[i,d] + rest[i,d,'週休'] == 1, f"SundayWorkOrWeeklyOff_{i}_{d}"

In [105]:
#土曜日に休む場合は非番
for i in I:
    for d in D_saturday:
        # もし (i,d) に特別休暇が指定されていればスキップ
        if (i, d) in pre_dict_rest:
            continue
        
        # 指定の休みが無い => 土曜は (出勤 or 非番)
        model += (
            y[(i,d)] + rest[(i,d,'非番')]
            == 1
        ), f"SaturdayWorkOrNonban_{i}_{d}"

In [106]:
#祝日以外の日は祝休を取れない
for i in I:
    for d in D:
        if d not in D_holiday:
            # 祝日以外の日 => 祝日休 は 0
            model += rest[i,d,'祝休'] == 0, f"NoHolidayRest_{i}_{d}"

In [107]:
# 祝日に非番の指定
for d in D_holiday:
    for i in I:
        #非番の指定があれば入れられる。
        if (i,d) in pre_dict_rest and pre_dict_rest[(i,d)] == '非番':
            continue
        #指定がなければ祝日は "出勤 or 祝休" のどちらか
        else:
            model += y[(i,d)] + rest[(i,d,'祝休')] == 1

In [108]:
#"""連勤に関する制約"""
#10連勤の禁止　廃休、マル超を取れば９連勤まで可
for i in I:
    # d_idxを 0..(28-10) までループ => 0..18
    for d_idx in range(len(D) - 10 + 1):  # 28-10+1=19
        # d_idx..d_idx+9 (10日分)
        consecutive_days = [D[d_idx + offset] for offset in range(10)]
        
        # y[(i, day)] を連続10日分集計
        model += (
            pulp.lpSum(y[(i, day_)] for day_ in consecutive_days)
            <= 9
        ), f"No10ConsecutiveDays_{i}_{d_idx}"
                
#紐付け制約: normal_work <= y, normal_work <= 1 - x_special
for i in I:
    for d in D:
        model += normal_work[(i,d)] >= y[(i,d)] - specialWork[(i,d,'廃休')] - specialWork[(i,d,'マル超')]
        model += normal_work[(i,d)] <= 1 - specialWork[(i,d,'廃休')]
        model += normal_work[(i,d)] <= 1 - specialWork[(i,d,'マル超')]
        

#廃休、マル超を取らない連勤は５まで。
for i in I:
    for start_idx in range(len(D) - 6 + 1):  # 0..22
        consecutive_dates = [D[start_idx + r] for r in range(6)]
        # ここで normal_work[(i, consecutive_dates[r])] を合計
        model += (
            pulp.lpSum(normal_work[(i, d_)] for d_ in consecutive_dates)
            <= 5
        )

In [109]:
#"""社員の出勤可能数と業務数の過不足を計算"""
# 1) 社員ごとの出勤可能日数を計算
# 1) 社員ごとの出勤可能日数を、C の可否から直接カウント
base = 20  # 最大勤務日数の上限

# avail[(i, d)] が 1 の日を数えて possible を計算し、上限をかける
employee_possible_days = {
    i: min(
        sum(avail[(i, d)] for d in D),
        base
    )
    for i in I
}

# 確認出力
for i, cnt in employee_possible_days.items():
    print(f"{i} の出勤可能日数: {cnt} 日")
for i in I:
    extra_rest_count = 0
        
    # (1-a) 特別休暇を差し引く
    for d in D:
        if (i, d) in pre_dict_rest:
            r_type = pre_dict_rest[(i, d)]
            if r_type in ['計年', '年休', '夏期', '冬期', '代休',
                            '承欠', '休職', '産休', '育休', '介護', '病休', 'その他']:
                extra_rest_count += 1
    # 仮での基本出勤可能日数
    employee_possible_days[i] -= extra_rest_count

    # (1-b) 廃休 or マル超 指定があれば +1
    for d in D:
        if (i, d) in pre_dict_special:
            s_type = pre_dict_special[(i,d)]
            if s_type in ['廃休','マル超']:
                employee_possible_days[i] += 1

# (1-c) 出張や研修など (reqにない業務) の事前指定があれば -1
for (i, d), k in pre_dict_work.items():
    if (d, k) not in req:
        # この業務に入ってもreqは満たせないため-1
        employee_possible_days[i] -= 1

# 2) 需要計算
# 2) 需要計算：req による実際の要出勤数を集計
#バランス調整用の補助20を引く
total_demand = sum(req.values()) - 20

print(f"【需要計算】total_demand = {total_demand} シフト枠")

#3) 供給計算
# 例: 全社員の出勤可能日数を合計
total_supply = sum(employee_possible_days.values())

# 4) 過不足を計算
excess_or_deficiency = total_supply - total_demand
print(f"【出勤可能日数計算】")
for i in I:
    print(f"  - {i}: {employee_possible_days[i]}日")

print(f"total_supply={total_supply}")
# あるいはゼロを +0 と表示したくない場合は条件分岐で制御
sign = '+' if excess_or_deficiency > 0 else ''
print(f"過不足 = {sign}{excess_or_deficiency}")

1 の出勤可能日数: 19 日
2 の出勤可能日数: 20 日
3 の出勤可能日数: 20 日
4 の出勤可能日数: 20 日
5 の出勤可能日数: 20 日
6 の出勤可能日数: 19 日
7 の出勤可能日数: 19 日
8 の出勤可能日数: 11 日
9 の出勤可能日数: 19 日
10 の出勤可能日数: 19 日
【需要計算】total_demand = 175 シフト枠
【出勤可能日数計算】
  - 1: 19日
  - 2: 20日
  - 3: 20日
  - 4: 20日
  - 5: 20日
  - 6: 19日
  - 7: 19日
  - 8: 11日
  - 9: 19日
  - 10: 19日
total_supply=186
過不足 = +11

In [110]:
# 1) 対象となる業務種類リストを取得
selected_jobs = df_zone.loc[
    df_zone['稼働'].isin(['通配', '混合', '組立']),
    '区名'
].tolist()

# 2) 月～祝の列だけ抽出して、業務種類をインデックスにセット
subset = df_zone.loc[
    df_zone['区名'].isin(selected_jobs),
    ['区名', '月', '火', '水', '木', '金', '土', '日', '祝']
].set_index('区名')

#すべての曜日＋祝日の優先度を設定
# 3) 辞書化（orient='index' で {業務種類: {'月':…, …, '祝':…}, …} の形に）
job_availability = subset.to_dict(orient='index')
job_availability

{'1区': {'月': 10, '火': 10, '水': 10, '木': 10, '金': 10, '土': 0, '日': 0, '祝': 0},
 '2区': {'月': 10, '火': 10, '水': 10, '木': 10, '金': 10, '土': 0, '日': 0, '祝': 0},
 '3区': {'月': 10, '火': 10, '水': 10, '木': 10, '金': 10, '土': 0, '日': 0, '祝': 0},
 '4区': {'月': 10, '火': 9, '水': 9, '木': 9, '金': 9, '土': 0, '日': 0, '祝': 0},
 '大口1': {'月': 10, '火': 10, '水': 10, '木': 10, '金': 10, '土': 0, '日': 0, '祝': 0},
 '大口1-3': {'月': 10, '火': 8, '水': 8, '木': 9, '金': 9, '土': 0, '日': 0, '祝': 0},
 '補助': {'月': 1, '火': 1, '水': 1, '木': 1, '金': 1, '土': 10, '日': 0, '祝': 1},
 '速早': {'月': 0, '火': 0, '水': 0, '木': 0, '金': 0, '土': 10, '日': 10, '祝': 10},
 '速夜': {'月': 10, '火': 10, '水': 10, '木': 10, '金': 10, '土': 0, '日': 0, '祝': 0},
 '速夜(土)': {'月': 0, '火': 0, '水': 0, '木': 0, '金': 0, '土': 10, '日': 0, '祝': 0},
 '速夜(日)': {'月': 0, '火': 0, '水': 0, '木': 0, '金': 0, '土': 0, '日': 10, '祝': 0},
 '速夜(祝)': {'月': 0, '火': 0, '水': 0, '木': 0, '金': 0, '土': 0, '日': 0, '祝': 10},
 '組立': {'月': 1, '火': 1, '水': 1, '木': 1, '金': 1, '土': 0, '日': 0, '祝': 0}}

In [204]:
# 2) 全ての日×業務に対して base_priority を設定
# 業務の優先度
priority_map = {
    (d, k): job_availability.get(k, {}).get(date_label[d], 0)
    for (d, k) in req.keys()
}

In [194]:
priority_map

{(Timestamp('2025-11-16 00:00:00'), '速早'): 10,
 (Timestamp('2025-11-16 00:00:00'), '速夜(日)'): 10,
 (Timestamp('2025-11-17 00:00:00'), '1区'): 10,
 (Timestamp('2025-11-17 00:00:00'), '2区'): 10,
 (Timestamp('2025-11-17 00:00:00'), '3区'): 10,
 (Timestamp('2025-11-17 00:00:00'), '4区'): 10,
 (Timestamp('2025-11-17 00:00:00'), '大口1'): 10,
 (Timestamp('2025-11-17 00:00:00'), '大口1-3'): 10,
 (Timestamp('2025-11-17 00:00:00'), '補助'): 1,
 (Timestamp('2025-11-17 00:00:00'), '速夜'): 10,
 (Timestamp('2025-11-17 00:00:00'), '組立'): 1,
 (Timestamp('2025-11-18 00:00:00'), '1区'): 10,
 (Timestamp('2025-11-18 00:00:00'), '2区'): 10,
 (Timestamp('2025-11-18 00:00:00'), '3区'): 10,
 (Timestamp('2025-11-18 00:00:00'), '4区'): 9,
 (Timestamp('2025-11-18 00:00:00'), '大口1'): 10,
 (Timestamp('2025-11-18 00:00:00'), '大口1-3'): 8,
 (Timestamp('2025-11-18 00:00:00'), '補助'): 1,
 (Timestamp('2025-11-18 00:00:00'), '速夜'): 10,
 (Timestamp('2025-11-18 00:00:00'), '組立'): 1,
 (Timestamp('2025-11-19 00:00:00'), '1区'): 10,
 (Timestamp('2025-11-19 00:00:00'), '2区'): 10,
 (Timestamp('2025-11-19 00:00:00'), '3区'): 10,
 (Timestamp('2025-11-19 00:00:00'), '4区'): 9,
 (Timestamp('2025-11-19 00:00:00'), '大口1'): 10,
 (Timestamp('2025-11-19 00:00:00'), '大口1-3'): 8,
 (Timestamp('2025-11-19 00:00:00'), '補助'): 1,
 (Timestamp('2025-11-19 00:00:00'), '速夜'): 10,
 (Timestamp('2025-11-19 00:00:00'), '組立'): 1,
 (Timestamp('2025-11-20 00:00:00'), '1区'): 10,
 (Timestamp('2025-11-20 00:00:00'), '2区'): 10,
 (Timestamp('2025-11-20 00:00:00'), '3区'): 10,
 (Timestamp('2025-11-20 00:00:00'), '4区'): 9,
 (Timestamp('2025-11-20 00:00:00'), '大口1'): 10,
 (Timestamp('2025-11-20 00:00:00'), '大口1-3'): 9,
 (Timestamp('2025-11-20 00:00:00'), '補助'): 1,
 (Timestamp('2025-11-20 00:00:00'), '速夜'): 10,
 (Timestamp('2025-11-20 00:00:00'), '組立'): 1,
 (Timestamp('2025-11-21 00:00:00'), '1区'): 10,
 (Timestamp('2025-11-21 00:00:00'), '2区'): 10,
 (Timestamp('2025-11-21 00:00:00'), '3区'): 10,
 (Timestamp('2025-11-21 00:00:00'), '4区'): 9,
 (Timestamp('2025-11-21 00:00:00'), '大口1'): 10,
 (Timestamp('2025-11-21 00:00:00'), '大口1-3'): 9,
 (Timestamp('2025-11-21 00:00:00'), '補助'): 1,
 (Timestamp('2025-11-21 00:00:00'), '速夜'): 10,
 (Timestamp('2025-11-21 00:00:00'), '組立'): 1,
 (Timestamp('2025-11-22 00:00:00'), '補助'): 10,
 (Timestamp('2025-11-22 00:00:00'), '速早'): 10,
 (Timestamp('2025-11-22 00:00:00'), '速夜(土)'): 10,
 (Timestamp('2025-11-23 00:00:00'), '速早'): 10,
 (Timestamp('2025-11-23 00:00:00'), '速夜(日)'): 0,
 (Timestamp('2025-11-24 00:00:00'), '補助'): 1,
 (Timestamp('2025-11-24 00:00:00'), '速早'): 10,
 (Timestamp('2025-11-24 00:00:00'), '速夜(祝)'): 10,
 (Timestamp('2025-11-25 00:00:00'), '1区'): 10,
 (Timestamp('2025-11-25 00:00:00'), '2区'): 10,
 (Timestamp('2025-11-25 00:00:00'), '3区'): 10,
 (Timestamp('2025-11-25 00:00:00'), '4区'): 9,
 (Timestamp('2025-11-25 00:00:00'), '大口1'): 10,
 (Timestamp('2025-11-25 00:00:00'), '大口1-3'): 8,
 (Timestamp('2025-11-25 00:00:00'), '補助'): 1,
 (Timestamp('2025-11-25 00:00:00'), '速夜'): 10,
 (Timestamp('2025-11-25 00:00:00'), '組立'): 1,
 (Timestamp('2025-11-26 00:00:00'), '1区'): 10,
 (Timestamp('2025-11-26 00:00:00'), '2区'): 10,
 (Timestamp('2025-11-26 00:00:00'), '3区'): 10,
 (Timestamp('2025-11-26 00:00:00'), '4区'): 9,
 (Timestamp('2025-11-26 00:00:00'), '大口1'): 10,
 (Timestamp('2025-11-26 00:00:00'), '大口1-3'): 8,
 (Timestamp('2025-11-26 00:00:00'), '補助'): 1,
 (Timestamp('2025-11-26 00:00:00'), '速夜'): 10,
 (Timestamp('2025-11-26 00:00:00'), '組立'): 1,
 (Timestamp('2025-11-27 00:00:00'), '1区'): 10,
 (Timestamp('2025-11-27 00:00:00'), '2区'): 10,
 (Timestamp('2025-11-27 00:00:00'), '3区'): 10,
 (Timestamp('2025-11-27 00:00:00'), '4区'): 9,
 (Timestamp('2025-11-27 00:00:00'), '大口1'): 10,
 (Timestamp('2025-11-27 00:00:00'), '大口1-3'): 9,
 (Timestamp('2025-11-27 00:00:00'), '補助'): 1,
 (Timestamp('2025-11-27 00:00:00'), '速夜'): 10,
 (Timestamp('2025-11-27 00:00:00'), '組立'): 1,
 (Timestamp('2025-11-28 00:00:00'), '1区'): 10,
 (Timestamp('2025-11-28 00:00:00'), '2区'): 10,
 (Timestamp('2025-11-28 00:00:00'), '3区'): 10,
 (Timestamp('2025-11-28 00:00:00'), '4区'): 9,
 (Timestamp('2025-11-28 00:00:00'), '大口1'): 10,
 (Timestamp('2025-11-28 00:00:00'), '大口1-3'): 9,
 (Timestamp('2025-11-28 00:00:00'), '補助'): 1,
 (Timestamp('2025-11-28 00:00:00'), '速夜'): 10,
 (Timestamp('2025-11-28 00:00:00'), '組立'): 1,
 (Timestamp('2025-11-29 00:00:00'), '補助'): 10,
 (Timestamp('2025-11-29 00:00:00'), '速早'): 10,
 (Timestamp('2025-11-29 00:00:00'), '速夜(土)'): 10,
 (Timestamp('2025-11-30 00:00:00'), '速早'): 10,
 (Timestamp('2025-11-30 00:00:00'), '速夜(日)'): 10,
 (Timestamp('2025-12-01 00:00:00'), '1区'): 10,
 (Timestamp('2025-12-01 00:00:00'), '2区'): 10,
 (Timestamp('2025-12-01 00:00:00'), '3区'): 10,
 (Timestamp('2025-12-01 00:00:00'), '4区'): 10,
 (Timestamp('2025-12-01 00:00:00'), '大口1'): 10,
 (Timestamp('2025-12-01 00:00:00'), '大口1-3'): 10,
 (Timestamp('2025-12-01 00:00:00'), '補助'): 1,
 (Timestamp('2025-12-01 00:00:00'), '速夜'): 10,
 (Timestamp('2025-12-01 00:00:00'), '組立'): 1,
 (Timestamp('2025-12-02 00:00:00'), '1区'): 10,
 (Timestamp('2025-12-02 00:00:00'), '2区'): 10,
 (Timestamp('2025-12-02 00:00:00'), '3区'): 10,
 (Timestamp('2025-12-02 00:00:00'), '4区'): 9,
 (Timestamp('2025-12-02 00:00:00'), '大口1'): 10,
 (Timestamp('2025-12-02 00:00:00'), '大口1-3'): 8,
 (Timestamp('2025-12-02 00:00:00'), '補助'): 1,
 (Timestamp('2025-12-02 00:00:00'), '速夜'): 10,
 (Timestamp('2025-12-02 00:00:00'), '組立'): 1,
 (Timestamp('2025-12-03 00:00:00'), '1区'): 10,
 (Timestamp('2025-12-03 00:00:00'), '2区'): 10,
 (Timestamp('2025-12-03 00:00:00'), '3区'): 10,
 (Timestamp('2025-12-03 00:00:00'), '4区'): 9,
 (Timestamp('2025-12-03 00:00:00'), '大口1'): 10,
 (Timestamp('2025-12-03 00:00:00'), '大口1-3'): 8,
 (Timestamp('2025-12-03 00:00:00'), '補助'): 1,
 (Timestamp('2025-12-03 00:00:00'), '速夜'): 10,
 (Timestamp('2025-12-03 00:00:00'), '組立'): 1,
 (Timestamp('2025-12-04 00:00:00'), '1区'): 10,
 (Timestamp('2025-12-04 00:00:00'), '2区'): 10,
 (Timestamp('2025-12-04 00:00:00'), '3区'): 10,
 (Timestamp('2025-12-04 00:00:00'), '4区'): 9,
 (Timestamp('2025-12-04 00:00:00'), '大口1'): 10,
 (Timestamp('2025-12-04 00:00:00'), '大口1-3'): 9,
 (Timestamp('2025-12-04 00:00:00'), '補助'): 1,
 (Timestamp('2025-12-04 00:00:00'), '速夜'): 10,
 (Timestamp('2025-12-04 00:00:00'), '組立'): 1,
 (Timestamp('2025-12-05 00:00:00'), '1区'): 10,
 (Timestamp('2025-12-05 00:00:00'), '2区'): 10,
 (Timestamp('2025-12-05 00:00:00'), '3区'): 10,
 (Timestamp('2025-12-05 00:00:00'), '4区'): 9,
 (Timestamp('2025-12-05 00:00:00'), '大口1'): 10,
 (Timestamp('2025-12-05 00:00:00'), '大口1-3'): 9,
 (Timestamp('2025-12-05 00:00:00'), '補助'): 1,
 (Timestamp('2025-12-05 00:00:00'), '速夜'): 10,
 (Timestamp('2025-12-05 00:00:00'), '組立'): 1,
 (Timestamp('2025-12-06 00:00:00'), '補助'): 10,
 (Timestamp('2025-12-06 00:00:00'), '速早'): 10,
 (Timestamp('2025-12-06 00:00:00'), '速夜(土)'): 10,
 (Timestamp('2025-12-07 00:00:00'), '速早'): 10,
 (Timestamp('2025-12-07 00:00:00'), '速夜(日)'): 10,
 (Timestamp('2025-12-08 00:00:00'), '1区'): 10,
 (Timestamp('2025-12-08 00:00:00'), '2区'): 10,
 (Timestamp('2025-12-08 00:00:00'), '3区'): 10,
 (Timestamp('2025-12-08 00:00:00'), '4区'): 10,
 (Timestamp('2025-12-08 00:00:00'), '大口1'): 10,
 (Timestamp('2025-12-08 00:00:00'), '大口1-3'): 10,
 (Timestamp('2025-12-08 00:00:00'), '補助'): 1,
 (Timestamp('2025-12-08 00:00:00'), '速夜'): 10,
 (Timestamp('2025-12-08 00:00:00'), '組立'): 1,
 (Timestamp('2025-12-09 00:00:00'), '1区'): 10,
 (Timestamp('2025-12-09 00:00:00'), '2区'): 10,
 (Timestamp('2025-12-09 00:00:00'), '3区'): 10,
 (Timestamp('2025-12-09 00:00:00'), '4区'): 9,
 (Timestamp('2025-12-09 00:00:00'), '大口1'): 10,
 (Timestamp('2025-12-09 00:00:00'), '大口1-3'): 8,
 (Timestamp('2025-12-09 00:00:00'), '補助'): 1,
 (Timestamp('2025-12-09 00:00:00'), '速夜'): 10,
 (Timestamp('2025-12-09 00:00:00'), '組立'): 1,
 (Timestamp('2025-12-10 00:00:00'), '1区'): 10,
 (Timestamp('2025-12-10 00:00:00'), '2区'): 10,
 (Timestamp('2025-12-10 00:00:00'), '3区'): 10,
 (Timestamp('2025-12-10 00:00:00'), '4区'): 9,
 (Timestamp('2025-12-10 00:00:00'), '大口1'): 10,
 (Timestamp('2025-12-10 00:00:00'), '大口1-3'): 8,
 (Timestamp('2025-12-10 00:00:00'), '補助'): 1,
 (Timestamp('2025-12-10 00:00:00'), '速夜'): 10,
 (Timestamp('2025-12-10 00:00:00'), '組立'): 1,
 (Timestamp('2025-12-11 00:00:00'), '1区'): 10,
 (Timestamp('2025-12-11 00:00:00'), '2区'): 10,
 (Timestamp('2025-12-11 00:00:00'), '3区'): 10,
 (Timestamp('2025-12-11 00:00:00'), '4区'): 9,
 (Timestamp('2025-12-11 00:00:00'), '大口1'): 10,
 (Timestamp('2025-12-11 00:00:00'), '大口1-3'): 9,
 (Timestamp('2025-12-11 00:00:00'), '補助'): 1,
 (Timestamp('2025-12-11 00:00:00'), '速夜'): 10,
 (Timestamp('2025-12-11 00:00:00'), '組立'): 1,
 (Timestamp('2025-12-12 00:00:00'), '1区'): 10,
 (Timestamp('2025-12-12 00:00:00'), '2区'): 10,
 (Timestamp('2025-12-12 00:00:00'), '3区'): 10,
 (Timestamp('2025-12-12 00:00:00'), '4区'): 9,
 (Timestamp('2025-12-12 00:00:00'), '大口1'): 10,
 (Timestamp('2025-12-12 00:00:00'), '大口1-3'): 9,
 (Timestamp('2025-12-12 00:00:00'), '補助'): 1,
 (Timestamp('2025-12-12 00:00:00'), '速夜'): 10,
 (Timestamp('2025-12-12 00:00:00'), '組立'): 1,
 (Timestamp('2025-12-13 00:00:00'), '補助'): 10,
 (Timestamp('2025-12-13 00:00:00'), '速早'): 10,
 (Timestamp('2025-12-13 00:00:00'), '速夜(土)'): 10}

In [113]:
LEAVE_DEDUCT = {
    '計年','年休','夏期','冬期','代休','承欠','休職','産休','育休','介護','病休','その他'
}
SPECIAL_ADD = {'廃休','マル超'}

BASE = 20
ADJUST_HELPER = 20

# 0) 日ごとの “働ける” を作る（ここを一本化）
def is_workable(i, d):
    # 週休/非番/祝休など「休み系」は False
    if (i, d) in pre_dict_rest:
        r = pre_dict_rest[(i, d)]
        if r in LEAVE_DEDUCT or r in {'非番','週休','祝休'}:
            return False
    return True

# 1) ベース供給（上限20）
employee_possible = {
    i: min(sum(1 for d in D if is_workable(i, d)), BASE)
    for i in I
}

# 2) 廃休/マル超（追加出勤扱い）
for i in I:
    add = sum(
        1 for d in D
        if (i, d) in pre_dict_special and pre_dict_special[(i, d)] in SPECIAL_ADD
    )
    employee_possible[i] += add

# 3) reqにない業務の事前指定（その日は埋まるので -1）
deduct_days = set()
for (i, d), k in pre_dict_work.items():
    if (d, k) not in req:
        deduct_days.add((i, d))
for (i, d) in deduct_days:
    employee_possible[i] -= 1

# 4) 需要
raw_demand = sum(req.values())
total_demand = raw_demand - ADJUST_HELPER

# 5) 合計
total_supply = sum(employee_possible.values())
excess = total_supply - total_demand

print("=== 社員ごとの出勤可能日数（供給） ===")
for i in sorted(employee_possible.keys()):
    print(f"{i:>6} : {employee_possible[i]:>3} 日")

print("-" * 40)
print(f"total_supply = {total_supply}")

print("\n=== 需要（req）の内訳 ===")
print(f"raw_demand (sum(req.values())) = {raw_demand}")
print(f"adjust_helper               = {ADJUST_HELPER}")
print(f"total_demand                = {total_demand}")

print("\n=== 供給 − 需要（過不足） ===")
sign = "+" if excess > 0 else ""
print(f"excess = {sign}{excess}")

if excess < 0:
    print("⚠️ 供給不足です（シフト成立不可の可能性あり）")
elif excess == 0:
    print("◎ 供給と需要が一致しています")
else:
    print("◯ 供給に余裕があります")

print("\n=== 調整要因サマリ ===")

# 廃休・マル超の合計
total_special_add = sum(
    1 for (i, d), v in pre_dict_special.items()
    if v in SPECIAL_ADD
)
print("廃休/マル超 合計日数 =", total_special_add)

# reqにない業務で引いた日数
print("reqにない業務で減算した日数 =", len(deduct_days))

# 休暇指定合計
print("休暇指定日数 =", len(pre_dict_rest))

=== 社員ごとの出勤可能日数（供給） ===
     1 :  20 日
     2 :  20 日
     3 :  20 日
     4 :  20 日
     5 :  20 日
     6 :  20 日
     7 :  20 日
     8 :  20 日
     9 :  20 日
    10 :  20 日
----------------------------------------
total_supply = 200

=== 需要（req）の内訳 ===
raw_demand (sum(req.values())) = 195
adjust_helper               = 20
total_demand                = 175

=== 供給 − 需要（過不足） ===
excess = +25
◯ 供給に余裕があります

=== 調整要因サマリ ===
廃休/マル超 合計日数 = 0
reqにない業務で減算した日数 = 0
休暇指定日数 = 10

In [114]:
# =========================
#  需要(demand) 日別：その日に稼働する区数
# =========================
# zones.csv の曜日列（想定）
DAYCOLS = ["月","火","水","木","金","土","日","祝"]

missing = [c for c in DAYCOLS if c not in df_zone.columns]
if missing:
    print("zones.csv columns =", df_zone.columns.tolist())
    raise ValueError(f"zones.csv に曜日列がありません: missing={missing}")

# 日付→曜日ラベル（祝なら"祝"、それ以外は月火水...、日曜は"日"）
JPWEEK = ["月","火","水","木","金","土","日"]

def day_label(d: pd.Timestamp) -> str:
    if jpholiday.is_holiday(d):
        return "祝"
    return JPWEEK[d.weekday()]  # 0=月…6=日

# zones.csv から「その日に稼働する区」を返す
def active_zones_for_day(lbl: str) -> list[str]:
    # 稼働が数値(10/0)でも文字でも、とにかく「0/空/NaN以外」を稼働扱いにする
    s = df_zone[[zone_name_col, lbl]].copy()
    s[zone_name_col] = s[zone_name_col].astype(str).str.strip()
    col = s[lbl]

    def is_active(v):
        if pd.isna(v):
            return False
        vstr = str(v).strip()
        if vstr == "" or vstr == "0":
            return False
        # "0.0"も除外
        try:
            if float(vstr) == 0.0:
                return False
        except:
            pass
        return True

    act = s.loc[col.map(is_active), zone_name_col].tolist()
    return act

# 日別 demand（区数）
demand_by_date = {}
active_zones_by_date = {}

for d in D:
    lbl = day_label(d)
    zones = active_zones_for_day(lbl)
    active_zones_by_date[d] = zones
    demand_by_date[d] = len(zones)

print("=== 日別 需要(demand) ===")
for d in D:
    print(d.strftime("%Y-%m-%d"), day_label(d), "demand=", demand_by_date[d])

print("total_demand =", sum(demand_by_date.values()))

=== 日別 需要(demand) ===
2025-11-16 日 demand= 2
2025-11-17 月 demand= 9
2025-11-18 火 demand= 9
2025-11-19 水 demand= 9
2025-11-20 木 demand= 9
2025-11-21 金 demand= 9
2025-11-22 土 demand= 3
2025-11-23 祝 demand= 3
2025-11-24 祝 demand= 3
2025-11-25 火 demand= 9
2025-11-26 水 demand= 9
2025-11-27 木 demand= 9
2025-11-28 金 demand= 9
2025-11-29 土 demand= 3
2025-11-30 日 demand= 2
2025-12-01 月 demand= 9
2025-12-02 火 demand= 9
2025-12-03 水 demand= 9
2025-12-04 木 demand= 9
2025-12-05 金 demand= 9
2025-12-06 土 demand= 3
2025-12-07 日 demand= 2
2025-12-08 月 demand= 9
2025-12-09 火 demand= 9
2025-12-10 水 demand= 9
2025-12-11 木 demand= 9
2025-12-12 金 demand= 9
2025-12-13 土 demand= 3
total_demand = 195

In [115]:
# =========================
#  供給(supply) 日別：出勤できる人数
# =========================
LEAVE_BLOCK = {
    "非番","週休","祝休",
    "計年","年休","夏期","冬期","代休","承欠","休職","産休","育休","介護","病休","その他"
}
SPECIAL_ADD = {"廃休","マル超"}  # 供給+1扱い（追加出勤）

# 全社員集合 I（emp_no）
I = sorted(df_emp[emp_no_col].astype(str).str.strip().unique().tolist()) if emp_no_col else sorted({k[0] for k in pre_dict_time.keys()} | {k[0] for k in pre_dict_rest.keys()} | {k[0] for k in pre_dict_work.keys()} | {k[0] for k in pre_dict_special.keys()})

def is_off(emp: str, d: pd.Timestamp) -> bool:
    # 下段に休みコードが入っていれば休み扱い
    v = pre_dict_rest.get((emp, d))
    if v is None:
        return False
    return v in LEAVE_BLOCK

# 日別供給：休みでない人を数える
supply_by_date = {}
off_count_by_date = {}
special_add_by_date = {}

for d in D:
    off = 0
    add = 0
    for emp in I:
        if is_off(emp, d):
            off += 1
        # 廃休/マル超は“追加出勤枠”として数える（あなたのロジック踏襲）
        if pre_dict_special.get((emp, d)) in SPECIAL_ADD:
            add += 1

    # 基本供給：社員数 - 休み人数
    base_supply = len(I) - off

    # 追加供給：廃休/マル超
    supply_by_date[d] = base_supply + add
    off_count_by_date[d] = off
    special_add_by_date[d] = add

print("=== 日別 供給(supply) ===")
for d in D:
    print(
        d.strftime("%Y-%m-%d"), day_label(d),
        "supply=", supply_by_date[d],
        "(off=", off_count_by_date[d], "add=", special_add_by_date[d], ")"
    )

print("total_supply =", sum(supply_by_date.values()))

=== 日別 供給(supply) ===
2025-11-16 日 supply= 10 (off= 0 add= 0 )
2025-11-17 月 supply= 10 (off= 0 add= 0 )
2025-11-18 火 supply= 10 (off= 0 add= 0 )
2025-11-19 水 supply= 9 (off= 1 add= 0 )
2025-11-20 木 supply= 10 (off= 0 add= 0 )
2025-11-21 金 supply= 9 (off= 1 add= 0 )
2025-11-22 土 supply= 10 (off= 0 add= 0 )
2025-11-23 祝 supply= 10 (off= 0 add= 0 )
2025-11-24 祝 supply= 10 (off= 0 add= 0 )
2025-11-25 火 supply= 10 (off= 0 add= 0 )
2025-11-26 水 supply= 9 (off= 1 add= 0 )
2025-11-27 木 supply= 10 (off= 0 add= 0 )
2025-11-28 金 supply= 10 (off= 0 add= 0 )
2025-11-29 土 supply= 6 (off= 4 add= 0 )
2025-11-30 日 supply= 10 (off= 0 add= 0 )
2025-12-01 月 supply= 10 (off= 0 add= 0 )
2025-12-02 火 supply= 9 (off= 1 add= 0 )
2025-12-03 水 supply= 10 (off= 0 add= 0 )
2025-12-04 木 supply= 10 (off= 0 add= 0 )
2025-12-05 金 supply= 10 (off= 0 add= 0 )
2025-12-06 土 supply= 10 (off= 0 add= 0 )
2025-12-07 日 supply= 10 (off= 0 add= 0 )
2025-12-08 月 supply= 9 (off= 1 add= 0 )
2025-12-09 火 supply= 9 (off= 1 add= 0 )
2025-12-10 水 supply= 10 (off= 0 add= 0 )
2025-12-11 木 supply= 10 (off= 0 add= 0 )
2025-12-12 金 supply= 10 (off= 0 add= 0 )
2025-12-13 土 supply= 10 (off= 0 add= 0 )
total_supply = 270

In [123]:
BASE = 20
ADJUST_HELPER = 20

LEAVE_DEDUCT = {
    "計年","年休","夏期","冬期","代休",
    "承欠","休職","産休","育休","介護","病休","その他"
}
SPECIAL_ADD = {"廃休","マル超"}

# ---------------------------------------
# 1) 社員ごとの出勤可能日数（供給）
# ---------------------------------------
missing = 0

employee_possible_days = {}
for i in I:
    s = 0
    for d in D:
        v = avail.get((i, d), None)
        if v is None:
            missing += 1
            v = 0
        s += int(v)
    employee_possible_days[i] = min(s, BASE)

print("avail missing count =", missing)  # 0が理想

# (1-a) 特別休暇を差し引く（※週休/非番/祝休は avail 側で0にしている前提）
for i in I:
    extra_rest_count = 0
    for d in D:
        r_type = pre_dict_rest.get((i, d))
        if r_type in LEAVE_DEDUCT:
            extra_rest_count += 1
    employee_possible_days[i] -= extra_rest_count

# (1-b) 廃休 / マル超 は +1（追加出勤扱い）
for i in I:
    add = 0
    for d in D:
        s_type = pre_dict_special.get((i, d))
        if s_type in SPECIAL_ADD:
            add += 1
    employee_possible_days[i] += add

# (1-c) reqにない業務は -1（同一日重複を防ぐ）
reqout_days = set()
for (i, d), k in pre_dict_work.items():
    if (d, k) not in req:
        reqout_days.add((i, d))

for (i, d) in reqout_days:
    employee_possible_days[i] -= 1

# ---------------------------------------
# 2) 需要
# ---------------------------------------
raw_demand = sum(req.values())
total_demand = raw_demand - ADJUST_HELPER
print(f"【需要計算】raw={raw_demand}, adjust={ADJUST_HELPER}, total_demand={total_demand} シフト枠")

# ---------------------------------------
# 3) 供給
# ---------------------------------------
total_supply = sum(employee_possible_days.values())

# ---------------------------------------
# 4) 過不足
# ---------------------------------------
excess_or_deficiency = total_supply - total_demand

print("【出勤可能日数計算】")
for i in I:
    print(f"  - {i}: {employee_possible_days[i]}日")

print(f"total_supply={total_supply}")
sign = '+' if excess_or_deficiency > 0 else ''
print(f"過不足 = {sign}{excess_or_deficiency}")

avail missing count = 0
【需要計算】raw=194, adjust=20, total_demand=174 シフト枠
【出勤可能日数計算】
  - 1: 18日
  - 10: 18日
  - 2: 19日
  - 3: 19日
  - 4: 19日
  - 5: 19日
  - 6: 18日
  - 7: 18日
  - 8: 10日
  - 9: 18日
total_supply=176
過不足 = +2

In [179]:
from posms.models_lagless.registered_plus import train_and_forecast_28d_from_csv

In [180]:
csv_path = csv_path = "/Users/hiraokatatsuru/Library/Mobile Documents/com~apple~CloudDocs/postal-operation-shift-management-system/db/init/csv/postal_datas.csv"

df_result, metrics = train_and_forecast_28d_from_csv(
    csv_path=csv_path,
    forecast_start="2025-11-16",
    days=28,
    train_end="2024-09-30",
    valid_end="2024-12-31",
)
df_result

         date  forecast_volume
0  2025-11-16             1182
1  2025-11-17              706
2  2025-11-18             1062
3  2025-11-19             1416
4  2025-11-20             1988
5  2025-11-21             1741
6  2025-11-22             1864
7  2025-11-23             1120
8  2025-11-24              707
9  2025-11-25             1062
10 2025-11-26             1416
11 2025-11-27             1988
12 2025-11-28             1741
13 2025-11-29             1663
14 2025-11-30             1182
15 2025-12-01              714
16 2025-12-02             1084
17 2025-12-03             1486
18 2025-12-04             2045
19 2025-12-05             1898
20 2025-12-06             1796
21 2025-12-07             1314
22 2025-12-08              714
23 2025-12-09             1084
24 2025-12-10             1486
25 2025-12-11             2045
26 2025-12-12             1898
27 2025-12-13             1796

In [181]:
from posms.models_lagless.normal import train_and_forecast_28d_from_csv
df_result_normal, metrics = train_and_forecast_28d_from_csv(
    csv_path=csv_path,
    forecast_start="2025-11-16",
    days=28,
)
df_result_normal

          date  forecast_volume
0   2025-11-16                0
1   2025-11-17            99000
2   2025-11-18            67000
3   2025-11-19            52000
4   2025-11-20            54000
5   2025-11-21            73000
6   2025-11-22                0
7   2025-11-23                0
8   2025-11-24                0
9   2025-11-25            74000
10  2025-11-26            52000
11  2025-11-27            54000
12  2025-11-28            73000
13  2025-11-29                0
14  2025-11-30                0
15  2025-12-01            86000
16  2025-12-02            64000
17  2025-12-03            50000
18  2025-12-04            60000
19  2025-12-05            58000
20  2025-12-06                0
21  2025-12-07                0
22  2025-12-08            86000
23  2025-12-09            64000
24  2025-12-10            50000
25  2025-12-11            60000
26  2025-12-12            58000
27  2025-12-13                0

In [200]:
# 除外したい区名
exclude = {'補助', '速早', '速夜', '組立','速夜(土)', '速夜(日)', '速夜(祝)'}

# job_availability（辞書）→ DataFrame化
ja = pd.DataFrame.from_dict(job_availability, orient='index')

# 月〜祝の列
dow_cols = ['月', '火', '水', '木', '金', '土', '日', '祝']

# 除外して、月〜祝を合計 → 小さい順に並べる
priority_series = (
    ja.loc[~ja.index.isin(exclude), dow_cols]
      .sum(axis=1)
      .sort_values(ascending=True)
)

# 欠区の優先区（小さい順）
missing_zone_priority = priority_series.index.tolist()

priority_series, missing_zone_priority

(大口1-3    44
 4区       46
 1区       50
 2区       50
 3区       50
 大口1      50
 dtype: int64,
 ['大口1-3', '4区', '1区', '2区', '3区', '大口1'])

In [205]:
# ============================================================
# 2) df_result_normal を date index に正規化
# ============================================================
df_n = df_result_normal.copy()
if "date" in df_n.columns:
    df_n["date"] = pd.to_datetime(df_n["date"]).dt.normalize()
    df_n = df_n.set_index("date")
else:
    df_n.index = pd.to_datetime(df_n.index).normalize()

s = df_n["forecast_volume"].reindex(pd.DatetimeIndex(D_weekday).normalize()).dropna()

# ============================================================
# 3) 上位5日・下位5日（平日）を抽出
# ============================================================
top5_days = s.sort_values(ascending=False).head(5)
bottom5_days = s.sort_values(ascending=True).head(5)

# ============================================================
# 5) priority_map を操作
#   - 上位5日: (d, '補助') を +（増やす）
#   - 下位5日: (d, z_min) を -1 する（補助は引かない）
# ============================================================
helper_zone = "補助"

# 上位5日：その日の補助を加点（強さは調整可）
top_bonuses = [5, 4, 3, 2, 1]
for d, bonus in zip(top5_days.index, top_bonuses):
    priority_map[(d, helper_zone)] = priority_map.get((d, helper_zone), 0) + bonus

# 下位5日：missing_zone_priority[0] を各日で -1
for d in bottom5_days.index:
    priority_map[(d, z_min)] = priority_map.get((d, z_min), 0) - 1

# ============================================================
# 6) 確認
# ============================================================
top5_days, bottom5_days, z_min, {
    k: v for k, v in priority_map.items()
    if (k[0] in set(top5_days.index) and k[1] == helper_zone) or (k[0] in set(bottom5_days.index) and k[1] == z_min)
}

(2025-11-17    99000
 2025-12-08    86000
 2025-12-01    86000
 2025-11-25    74000
 2025-11-21    73000
 Name: forecast_volume, dtype: int64,
 2025-12-03    50000
 2025-12-10    50000
 2025-11-19    52000
 2025-11-26    52000
 2025-11-20    54000
 Name: forecast_volume, dtype: int64,
 '大口1-3',
 {(Timestamp('2025-11-17 00:00:00'), '補助'): 6,
  (Timestamp('2025-11-19 00:00:00'), '大口1-3'): 7,
  (Timestamp('2025-11-20 00:00:00'), '大口1-3'): 8,
  (Timestamp('2025-11-21 00:00:00'), '補助'): 2,
  (Timestamp('2025-11-25 00:00:00'), '補助'): 3,
  (Timestamp('2025-11-26 00:00:00'), '大口1-3'): 7,
  (Timestamp('2025-12-01 00:00:00'), '補助'): 4,
  (Timestamp('2025-12-03 00:00:00'), '大口1-3'): 7,
  (Timestamp('2025-12-08 00:00:00'), '補助'): 5,
  (Timestamp('2025-12-10 00:00:00'), '大口1-3'): 7})

In [211]:
import os
import pandas as pd
from sqlalchemy import create_engine, text

eng = create_engine(os.environ["DATABASE_URL"])

df = pd.read_sql(
    text("""
    SELECT date, mail_kind, actual_volume, forecast_volume
    FROM mailvolume_by_type
    WHERE office_id=:o AND mail_kind=:k AND date BETWEEN :d1 AND :d2
    ORDER BY date
    """),
    eng,
    params={"o": 1, "k": "normal", "d1": "2025-11-17", "d2": "2025-12-14"},
    parse_dates=["date"],
)
df

         date mail_kind actual_volume  forecast_volume
0  2025-11-17    normal          None           194000
1  2025-11-18    normal          None            56000
2  2025-11-19    normal          None            64000
3  2025-11-20    normal          None            66000
4  2025-11-21    normal          None            68000
5  2025-11-22    normal          None                0
6  2025-11-23    normal          None                0
7  2025-11-24    normal          None                0
8  2025-11-25    normal          None           157000
9  2025-11-26    normal          None            41000
10 2025-11-27    normal          None            58000
11 2025-11-28    normal          None            66000
12 2025-11-29    normal          None                0
13 2025-11-30    normal          None                0
14 2025-12-01    normal          None           200000
15 2025-12-02    normal          None            46000
16 2025-12-03    normal          None            58000
17 2025-12-04    normal          None            72000
18 2025-12-05    normal          None            68000
19 2025-12-06    normal          None                0
20 2025-12-07    normal          None                0
21 2025-12-08    normal          None           185000
22 2025-12-09    normal          None            61000
23 2025-12-10    normal          None            67000
24 2025-12-11    normal          None            67000
25 2025-12-12    normal          None            66000
26 2025-12-13    normal          None                0
27 2025-12-14    normal          None                0

In [2]:
import os
os.environ["DATABASE_URL"] = "sqlite:////Users/hiraokatatsuru/Library/Mobile Documents/com~apple~CloudDocs/postal-operation-shift-management-system/db/posms.sqlite"

In [3]:
import os
import pandas as pd

# SQLite を使うなら（例）
# 例: os.environ["DATABASE_URL"] = "sqlite:////absolute/path/to/posms_demo.sqlite"
# Postgres なら DATABASE_URL or POSTGRES_* をセット済みの想定

from posms.features.builder import FeatureBuilder
from posms.models.rolling import rolling_forecast_28d
from posms.models.normal.predictor import ModelPredictor  # MLflowからロードするやつ

fb = FeatureBuilder(office_id=1, mail_kind="normal")  # office_idは適宜

# ModelPredictor は run_id / stage / model_name / tracking_uri をあなたの運用に合わせる
pred = ModelPredictor(
    stage="Production",
    model_name="posms",          # あなたのMLflow登録名に合わせる
    tracking_uri=None,           # 必要なら "http://localhost:15000" など
)

res = rolling_forecast_28d(
    fb=fb,
    predictor=pred,
    start="2026-03-01",  # 2月までしか実績が無くてもOKにするのが目的
    days=28,
    context_days=7,
)

res.as_of, res.start, res.end

/Users/hiraokatatsuru/miniconda3/envs/posms311/lib/python3.11/site-packages/mlflow/store/artifact/utils/models.py:31: FutureWarning: ``mlflow.tracking.client.MlflowClient.get_latest_versions`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages
  latest = client.get_latest_versions(name, None if stage is None else [stage])
2026/02/11 21:20:23 WARNING mlflow.utils.requirements_utils: Detected one or more mismatches between the model's dependencies and the current Python environment:
 - mlflow (current: 2.16.2, required: mlflow==2.22.1)
 - pandas (current: 2.2.3, required: pandas==2.3.2)
 - pyarrow (current: 17.0.0, required: pyarrow==19.0.1)
 - scikit-learn (current: 1.4.2, required: scikit-learn==1.7.1)
 - scipy (current: 1.13.1, required: scipy==1.16.1)
 - xgboost (current: 2.0.3, required: xgboost==2.1.4)
To fix the mismatches, call `mlflow.pyfunc.get_model_dependencies(model_uri)` to fetch the model's environment and install dependencies using the resulting environment file.
2026/02/11 21:20:23 WARNING mlflow.pyfunc: The version of Python that the model was saved in, `Python 3.12.9`, differs from the version of Python that is currently running, `Python 3.11.13`, and may be incompatible

OperationalError: (sqlite3.OperationalError) no such table: mailvolume_by_type
[SQL:
                SELECT "date", office_id, actual_volume, price_increase_flag
                FROM mailvolume_by_type
                WHERE office_id = ?
                  AND mail_kind = ?
                ORDER BY "date"
            ]
[parameters: (1, 'normal')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [1]:
import os

os.environ["DATABASE_URL"] = (
    "sqlite:////Users/hiraokatatsuru/Library/Mobile Documents/com~apple~CloudDocs/"
    "postal-operation-shift-management-system/excel_templates/posms_demo.db"
)

print(os.environ["DATABASE_URL"])

sqlite:////Users/hiraokatatsuru/Library/Mobile Documents/com~apple~CloudDocs/postal-operation-shift-management-system/excel_templates/posms_demo.db

In [6]:
from sqlalchemy import create_engine, inspect

engine = create_engine(os.environ["DATABASE_URL"], future=True)
insp = inspect(engine)

print("tables:", insp.get_table_names())
print("views :", insp.get_view_names())

tables: ['demandprofile', 'department', 'employee', 'employee_availabilities', 'employeezoneproficiency', 'holiday', 'jobtype', 'leavetype', 'mailvolume_by_type', 'office', 'shiftassignment', 'special_attendance_type', 'team', 'zone']
views : []

In [2]:
from posms.features.builder import FeatureBuilder
from posms.models.rolling import rolling_forecast_28d
from posms.models.normal.predictor import ModelPredictor

fb = FeatureBuilder(office_id=1, mail_kind="normal")

pred = ModelPredictor(
    stage="Production",
    model_name="posms",
    tracking_uri=None,   # ローカルMLflowなら "http://localhost:15000"
)

res = rolling_forecast_28d(
    fb=fb,
    predictor=pred,
    start="2026-03-01",
    days=28,
    context_days=7,
)

res.as_of, res.start, res.end

/Users/hiraokatatsuru/miniconda3/envs/posms311/lib/python3.11/site-packages/mlflow/store/artifact/utils/models.py:31: FutureWarning: ``mlflow.tracking.client.MlflowClient.get_latest_versions`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages
  latest = client.get_latest_versions(name, None if stage is None else [stage])
2026/02/11 21:46:36 WARNING mlflow.utils.requirements_utils: Detected one or more mismatches between the model's dependencies and the current Python environment:
 - mlflow (current: 2.16.2, required: mlflow==2.22.1)
 - pandas (current: 2.2.3, required: pandas==2.3.2)
 - pyarrow (current: 17.0.0, required: pyarrow==19.0.1)
 - scikit-learn (current: 1.4.2, required: scikit-learn==1.7.1)
 - scipy (current: 1.13.1, required: scipy==1.16.1)
 - xgboost (current: 2.0.3, required: xgboost==2.1.4)
To fix the mismatches, call `mlflow.pyfunc.get_model_dependencies(model_uri)` to fetch the model's environment and install dependencies using the resulting environment file.
2026/02/11 21:46:36 WARNING mlflow.pyfunc: The version of Python that the model was saved in, `Python 3.12.9`, differs from the version of Python that is currently running, `Python 3.11.13`, and may be incompatible

MlflowException: Failed to enforce schema of data '   dow   dow_sin  dow_cos  is_holiday  is_after_holiday  \
7  6.0 -0.781832  0.62349         1.0               1.0

   is_after_after_holiday  month  season  lag_1  lag_7  rolling_mean_7  \
7                     0.0    3.0     1.0    0.0    0.0         33000.0

   is_new_year  is_obon  price_increase_flag
7          0.0      0.0                  0.0  ' with schema '['weekday': float (required), 'holiday': float (required), 'is_obon': float (required), 'is_nenmatsu': float (required), 'sum_lag_1': float (required), 'sum_rm7': float (required), 'sum_lag_7': float (required)]'. Error: Model is missing inputs ['weekday', 'holiday', 'is_nenmatsu', 'sum_lag_1', 'sum_rm7', 'sum_lag_7']. Note that there were extra inputs: ['rolling_mean_7', 'is_holiday', 'dow_sin', 'season', 'lag_7', 'dow', 'lag_1', 'price_increase_flag', 'is_after_after_holiday', 'is_new_year', 'month', 'dow_cos', 'is_after_holiday']

In [3]:
from posms.models.normal.predictor import ModelPredictor

pred = ModelPredictor(stage="Production", model_name="posms", tracking_uri=None)

print("model_uri:", pred.model_uri)

m = pred._pyfunc_model  # デバッグ用途（private）
print("pyfunc loaded:", m is not None)

if m is not None:
    input_schema = m.metadata.get_input_schema()
    print("input_schema:", input_schema)
    required_cols = [c.name for c in input_schema.inputs]
    print("required_cols:", required_cols)
else:
    print("pyfuncではありません（xgboost/sklearnでロードされています）")

/Users/hiraokatatsuru/miniconda3/envs/posms311/lib/python3.11/site-packages/mlflow/store/artifact/utils/models.py:31: FutureWarning: ``mlflow.tracking.client.MlflowClient.get_latest_versions`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages
  latest = client.get_latest_versions(name, None if stage is None else [stage])
2026/02/11 21:53:22 WARNING mlflow.utils.requirements_utils: Detected one or more mismatches between the model's dependencies and the current Python environment:
 - mlflow (current: 2.16.2, required: mlflow==2.22.1)
 - pandas (current: 2.2.3, required: pandas==2.3.2)
 - pyarrow (current: 17.0.0, required: pyarrow==19.0.1)
 - scikit-learn (current: 1.4.2, required: scikit-learn==1.7.1)
 - scipy (current: 1.13.1, required: scipy==1.16.1)
 - xgboost (current: 2.0.3, required: xgboost==2.1.4)
To fix the mismatches, call `mlflow.pyfunc.get_model_dependencies(model_uri)` to fetch the model's environment and install dependencies using the resulting environment file.
2026/02/11 21:53:22 WARNING mlflow.pyfunc: The version of Python that the model was saved in, `Python 3.12.9`, differs from the version of Python that is currently running, `Python 3.11.13`, and may be incompatible

model_uri: runs:/74820882041d40048bfa6134c529ba1e/model
pyfunc loaded: True
input_schema: ['weekday': float (required), 'holiday': float (required), 'is_obon': float (required), 'is_nenmatsu': float (required), 'sum_lag_1': float (required), 'sum_rm7': float (required), 'sum_lag_7': float (required)]
required_cols: ['weekday', 'holiday', 'is_obon', 'is_nenmatsu', 'sum_lag_1', 'sum_rm7', 'sum_lag_7']